- tools/tpm2_ptool.py
This pull requests makes [tpm2_ptool](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/tools/tpm2_ptool.py) compatible with Python 3, while retaining Python 2 compatibility. The necessary changes are in separate commits for easier review:
1. Use `print` as a function instead of as a statement, available as a [future statement](https://docs.python.org/2/library/__future__.html) in Python 2.
2. Use [`dict.items()`](https://docs.python.org/2/library/stdtypes.html#dict.items) instead of [`dict.iteritems()`](https://docs.python.org/2/library/stdtypes.html#dict.iteritems) because the latter has been removed from Python 3, while the former works in both versions.
3. Cast `dict.values()` to a list because Python 3 returns a [view](https://docs.python.org/3/library/stdtypes.html#dict.values …
> Ensure Python 3 compatibility of tpm2_ptool

- tools/tpm2_ptool.py
This collection of commits contains some small fixes to correct two error messages, move files instead of renaming them (so it works when copying to another filesystem/mount) and defaulting to AES128 (see also https://github.com/tpm2-software/tpm2-tools/pull/1167 :wink:) as AES256 doesn't seem to be supported everywhere.
> Collection of small fixes for tpm2_ptool

- src/lib/tcti_ldr.c
The env variable TPM2_PKCS11_TCTI was being modified in place
causing subsequent library loads within the same applications
to fail, as the env string is modified. Copy it into a static
buffer.
Fixes: #26
> env: copy TPM2_PKCS11_TCTI rather then modifying it

- configure.ac
- m4/ax_check_enable_debug.m4
- m4/ax_is_release.m4
- src/lib/mutex.c
- src/lib/mutex.h
- src/lib/session_ctx.c
- src/lib/session_table.c
Pull in the ax_check_enable_debug and ax_is_release packages
to support the debug option.
The debug and release checks ensure that:
1. NDEBUG is set properly and thus assert works correctly
2. CFLAGS has:
* debug: -g and -O0
* release: -O2
> configure: add --enable-debug

- src/lib/slot.c
- src/lib/utils.h
Most of the PKCS#11 strings MUST NOT be NULL terminated and MUST be padded with ' '.
This patchset fixes a few places 
> Apply correct padding

- test/integration/pkcs-find-objects.int.c
- test/integration/pkcs-get-mechanism.int.c
- test/integration/pkcs-login-logout.int.c
- test/integration/pkcs-open-close-session.int.c
Corrects duplicate SPDX identifiers and incorect copyright dates.
Fixes: #42
> license: fix duplicate SPDX identifiers

- src/lib/db.c
- src/lib/object.c
- test/integration/pkcs-find-objects.int.c
- test/integration/scripts/create_pkcs_store.sh
- tools/tpm2_ptool.py
Peter Huewe (1):
C_FindObjectsInit: Return all objects if ulCount is 0
William Roberts (2):
tpm2_ptool.py: fix addtertiary variable name
db: add support for key labels
> add support for key labels and empty template find object calls

- src/lib/object.c
If a buffer is too small, it triggers an immediate return
without unlocking the session_ctx lock. Set the return
value in rv and goto out instead.
> C_GetAttributeInfo: fix deadlock

- src/lib/object.c
Fixes two cases when C_GetAttributeValue wasn't populating attributes
correctly.
The first case is when C_GetAttributeValue is called with a buffer bigger
than the actual attribute. The attributes length field needs to be set on
return so the caller knows the size. Previously the library assumed a caller
would always set the value pointer to NULL and populate all the size fields,
but this is NOT always the case.
The second case, is when C_GetAttributeValue fails to find data for an
attribute, that it shouldn't just skip it. It should set the size of
the attribute to 0 and the value pointer to NULL.
This patch also fixes the comparison for attribute buffer being too small.
It changes it from a not equal comparison to ensuring the found buffer is
less than or equal in size to the copy to …
> C_GetAttributeValue: fix attribute handling

- tools/tpm2_ptool.py
Spliting the string on , is incorrect as the seperator is
a newline (\n). Update this in the split.
> tpm2_ptool: fix bad kvp seperator in dict_from_kvp

- tools/tpm2_ptool.py
cmd.extend expects a list otherwise it will throw an exception.
> Pass arguments as a list to cmd.extend

- src/lib/db.c
- src/lib/token.c
- src/lib/token.h
- tools/tpm2_ptool.py
The patch below is a partial step towards supporting the C_Initialize() call. However, we will be re-configuring the auth model soon to support a different way of authorizing objects and performing pin-change. So before we go write the supporting pkcs11 side of this, we want to update the db, as more updates will likely be ensuing right behind this patch.
----
Add a commandlet that allows the creation of an empty token. This token can
be initialized later via a call to C_InitToken().
Example:
p11tool --list-tokens
Token 5:
URL: pkcs11:model=TPM2%20PKCS%2311;manufacturer=Intel;serial=0000000000000000;token=%28null%29
Label: (null)
Type: Hardware token
Manufacturer: Intel
Model: TPM2 PKCS#11
Serial: 0000000000000000
Module: libtpm2_pkcs11.so
Signed-off-by: William Roberts …
> tpm2_ptool.py: add commandlet for emptytoken

- configure.ac
- src/lib/twist.c
-fix cmocka dependency checks required even when --enable-unit is disabled
-fix twist compile error when UNIT_TESTING is not defined
Signed-off-by: Vincent Cao <vincent.t.cao@intel.com>
> Configure and twist: fix some build issues

- tools/tpm2_ptool.py
Two small fixes to ensure Python 3 compatibility of `tpm2_ptool.py`, which slipped through https://github.com/tpm2-software/tpm2-pkcs11/pull/45 and https://github.com/tpm2-software/tpm2-pkcs11/pull/54. With these modifications, the test suite passes using Python 3.
> tpm2_ptool.py: Python 3 compatibility

- src/lib/db.c
When not able to stat the db, the LOGV message was reporting
the base_path, which is either PKCS11_STORE_ENV_VAR or HOME
environment variables.
Use the full constructed path as constructed by snprintf().
> db: fix stat LOGV message

- configure.ac
- src/pkcs11.h
Despite section 2.1 of:
- http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959683
Stating:
Cryptoki structures are packed to occupy as little space as is possible.
Cryptoki structures SHALL be packed with 1-byte alignment.
Linux seems to not pack the structures. On a 64 bit machine, for instance
C_Initialize in libp11-kit's pkcs11 header file is at offset 8, versus offset
2. The only thing in-front of the C_Initialize function pointer is 2 char
inline version structure.
Stop packing on Linux, detect Windows and allow a FORCE_PACK option via
configure --enable-force-pack.
> pkcs11.h: structure packing: dont do it on linux

- docs/BUILDING.md
As suggested in https://github.com/tpm2-software/tpm2-pkcs11/issues/63#issuecomment-435952810, this PR documents the need to rebuild [`src/lib/twist.c`](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/src/lib/twist.c) when enabling unit tests.
> docs: instructions to rebuild twist.c when enabling unit tests

- src/lib/mutex.c
- src/lib/session.c
- src/lib/session_ctx.c
- src/lib/session_ctx.h
- src/lib/token.h
- test/integration/pkcs-login-logout.int.c
Login events need to be tracked at token scope in order
to set initial states of new sessions. Correct this
and add a test.
Fixes: #81
> session: track login/logout event at token scope

- Makefile.am
- src/lib/encrypt.c
- src/lib/encrypt.h
- src/lib/session_ctx.c
- src/pkcs11.c
- test/integration/pkcs-crypt.int.c
* Restores the symmetric crypto test
* Fixes a session state bug when clearing db initialized data on secondary and tertiary objects
* Adds a test for C_Encrypt and C_Decrypt oneshot interfaces
> Symmetric crypto fixes

- src/lib/key.c
It's not implemented, just stubbed in and un-tested. Just
return CKR_FUNCTION_NOT_SUPPORTED for now so applications
don't get confused.
Fixes: #85
> C_GenerateKeyPair: return CKR_FUNCTION_NOT_SUPPORTED

- src/lib/db.c
- src/lib/digest.c
- src/lib/digest.h
- src/lib/encrypt.c
- src/lib/encrypt.h
- src/lib/general.c
- src/lib/key.c
- src/lib/key.h
- src/lib/object.c
- src/lib/object.h
- src/lib/random.c
- src/lib/random.h
- src/lib/session.c
- src/lib/session.h
- src/lib/session_ctx.c
- src/lib/session_ctx.h
- src/lib/session_table.c
- src/lib/session_table.h
- src/lib/sign.c
- src/lib/sign.h
- src/lib/slot.h
- src/lib/token.c
- src/lib/token.h
- src/lib/tpm.c
- src/lib/tpm.h
- src/pkcs11.c
- test/integration/pkcs-misc.int.c
This makes progress on simplifying the internal design. We need to perhaps look at killing off the token * in session_ctx, as the token * is going to come down to R/O portions and session shared R/W data that needs to be locked. So clarifying this relationship and hiding data will help make the locking issues easier to solve.
Fixes: #6 
Fixes: #95 
Fixes: #75
> Token based tpm context, kill of cached session context and fix locking

- src/lib/digest.c
- src/lib/digest.h
- src/lib/sign.c
- src/lib/tpm.c
- src/lib/utils.c
- src/lib/utils.h
- test/integration/pkcs-sign-verify.int.c
When the TPM doesn't support the hashing algorithm requested
and subsequently the signing scheme selected using that hash,
synthesize it with software by:
1. Performing the digest in SW
2. Building the appropriate signing structure (PKCS v1.5 supported ONLY)
3. Apply the padding if needed (PKCS v1.5 supported ONLY)
4. Use raw RSA Decrypt (encrypt with private key)
Fixes: #4
> Software Based hash when not supported

- docs/BUILDING.md
- test/integration/scripts/create_pkcs_store.sh
Multiple integration tests can be run in parallel, but only one file `primary.ctx` is used for all of them in [`create_pkcs_store.sh`](https://github.com/tpm2-software/tpm2-pkcs11/blob/5be9faf7399b18e1f4f363af3d455e08eb17aba4/test/integration/scripts/create_pkcs_store.sh#L59). On my system, this leads to errors of the form
```
ERROR: Tss2_Sys_ContextLoad(0x1DF) - tpm:parameter(1):integrity check failed
ERROR: Could not load object, got: "primary.ctx"
ERROR: Unable to run tpm2_evictcontrol
```
when multiple tests try to write to that file at once. This is easily fixed by using separate files per test in the `$TPM2_PKCS11_STORE` directory.
In unrelated news, remove the instructions to rebuild `twist.c` because this is not necessary any more since #96 switched to using `config.h`.
>  test: fix race condition in create_pkcs_store.sh

- src/lib/db.c
- src/lib/encrypt.c
- src/lib/encrypt.h
- src/lib/object.c
- src/lib/object.h
- src/lib/session_ctx.c
- src/lib/sign.c
- src/lib/tpm.c
- src/lib/tpm.h
- test/integration/pkcs-crypt.int.c
- tools/tpm2_ptool.py
Refactor the internals to support RSA OAEP encryption via the
C_Encrypt/C_Decrypt interfaces. Currently, OAEP is limited to
what the TPM objects will support:
1. hashalg *MUST* be the namealg of the RSA object.
2. The mgf *MUST* be MGF1.
In the future, we could possibly synthesize it if not supported
directly via the TPM, just like PKCS Signing scheme.
Fixes #91
> rsa: support OAEP encryption

- test/integration/scripts/create_pkcs_store.sh
- tools/tpm2_ptool.py
Implement the "changepin" functionality. This allows a user
or so to change their pin IF they know the old pin. It does
so by updating the Software Wrapping key for the primary
object auth value, as well as updating the auth value for
the coresponding users sealing object via tpm2_changeauth.
It re-populated the coresponding db fields with the new
information.
> tpm2_ptool.py: implement changepin

- src/lib/db.c
- src/lib/tpm.c
- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/commandlets_store.py
- tools/tpm2_pkcs11/commandlets_token.py
- tools/tpm2_pkcs11/db.py
- tools/tpm2_pkcs11/tpm2.py
- tools/tpm2_pkcs11/tpm2_ptool.py
- tools/tpm2_pkcs11/utils.py
- tools/tpm2_ptool.py
** This will require a db delete and restore **
Having the public and private tpm data in files with paths in the DB itself
makes creating new objects that much more difficult as one needs to deal with
the myriad of filesystem issues. It would be much simpler to just store the
blob data in the DB, and should be faster:
- https://www.sqlite.org/intern-v-extern-blob.html
> db: store tpm pub/priv data in db

- src/lib/tpm.c
since mfg does not make sense in this context, rename it to the correct one: mgf
> Rename mfg to mgf

- src/lib/slot.c
This patch corrects the values and amount of data returned by C_GetMechanismList.
It must return the number of entries (ARRAY_LEN(mechs)) in *count and copy the correct number of bytes to the caller (sizeof(mechs)).
This was mixed up and was causing a buffer overflow / leakage.
> Return the correct amount of mechanisms

- test/integration/pkcs-sign-verify.int.c
Fix the following error when compiling with GCC 8.2.1:
```
test/integration/pkcs-sign-verify.int.c: In function ‘template_to_rsa_pub_key’:
test/integration/pkcs-sign-verify.int.c:703:1: error: label ‘error’ defined but not used [-Werror=unused-label]
error:
^~~~~
test/integration/pkcs-sign-verify.int.c:671:10: error: unused variable ‘ret’ [-Werror=unused-variable]
bool ret = false;
^~~
[...]
cc1: all warnings being treated as errors
```
> test: remove unused variable and label

- Makefile.am
- src/lib/digest.c
- src/lib/digest.h
- src/lib/encrypt.c
- src/lib/encrypt.h
- src/lib/key.c
- src/lib/key.h
- src/lib/object.c
- src/lib/object.h
- src/lib/random.c
- src/lib/random.h
- src/lib/session.c
- src/lib/session.h
- src/lib/session_ctx.c
- src/lib/session_ctx.h
- src/lib/session_table.c
- src/lib/sign.c
- src/lib/sign.h
- src/lib/token.c
- src/lib/token.h
- src/pkcs11.c
- test/integration/pkcs-session-state.c
Operation state for things like CKR_OPERATION_ACTIVE should be
session scope, not token scope. Correct this by moving opdata
managment back into the session_ctx structure. Also, since some
memory leaks occur if C_Logout() and C_CloseSession() are not
called, and entangled in the opdata managment, fix those leaks
as well.
Fixes: #142
> session_ctx: move opdata back from token scope

- configure.ac
For features enabled by default the output of “./configure --help” shall state how to disable them.
Printing on “./configure --help” --disable-X implies that by default the feature X is enabled.
> configure.ac: state on “./configure --help” how to disable the hardening

- configure.ac
Users assume, unless otherwise stated, that a ./configure feature has two states.  The output of “./configure --help” is supposed to state for features disabled by default, how to enable them, and for features enabled by default, how to disable them.
Printing --enable-X implies, that by default feature X is disabled.
> configure.ac: tweak output of “./configure --help”

- tools/tpm2_ptool
Fixes case like:
tpm2_ptool import --path 'path with space'
Signed-off-by: Markus Linnala <markus.linnala@gmail.com>
> tpm2_ptool: quote arguments properly

- configure.ac
* Replace variable hardening with enable_hardening, as the latter is filled implicitly by configure/AC_ARG_ENABLE and has the same purpose as the former.
* Typo
* Remove redundant code (AC_ARG_ENABLE(a, b, c, d) sets anyway enable_a to $enableval, so the third parameter can only do additional things)
> configure.ac: tweaks

- Makefile.am
see https://www.gnu.org/software/automake/manual/html_node/Default-_005fSOURCES.html.
> Makefile.am: delete default for test_unit_test_twist_SOURCES

- Makefile.am
From the Automake manual: “Files listed with the ‘_DATA’ primary are not automatically part of the tarball built with ‘make dist’”.
This means that `pkgconfig_DATA` and `nodist_pkgconfig_DATA` is the same.
> Makefile.am: remove nodist_ before pkgconfig_DATA

- src/lib/db.c
config.h needs to be included in order for configure --with-storedir to work.
Fixes: #29b2536f ("db: add search logic")
> Include config.h for --with-storedir to work

- docs/coding_standard_c.txt
- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/db.py
Coding standard says:
> Always use space characters, 4 spaces per level of indentation.
So fix it.
And then fix trailing whitespace introduced recently by 5b8be97ae93944249ffb0d8d10e025b65eb72e87
> Style fixes

- .ci/docker.run
- .ci/travis.run
- .travis.yml
The current codecov.io code coverage job in travis fails,
since the testing is done within a docker container and the
outside job cannot access the coverage reports.
https://docs.codecov.io/docs/testing-with-docker provides two solutions
for this - either copy the files via a shared folder, or just run
codecov within the container.
We now run it within the container, for this we need to install curl
first.
> Fix CodeCov.io Codecoverage

- src/lib/tpm.c
Sign failures from the tpm were retruning false through a CK_RV
return interface, thus indicating CKR_OK in the face of failure.
Correct this by returning CKR_GENERAL_ERROR.
> sign: fix error code condition

- .ci/docker.run
- src/lib/db.c
- src/lib/key.c
- src/lib/openssl_compat.c
- src/lib/openssl_compat.h
- src/lib/sign.c
- src/lib/tpm.c
- src/lib/tpm.h
- src/lib/utils.c
- src/lib/utils.h
- test/integration/pkcs-keygen.int.c
- test/integration/pkcs-sign-verify.int.c
- test/integration/test.h
* Probably want to copy the sign/verify bit to sign/verify tests as the sign/verify in keygen is really about ensuring that the objects function as intended post key generation.
> EC keygen and ECDSA sign and verify support

- src/pkcs11.c
auth_min_rw_so and the macro that called it have yet to be used, so
remove them to prevent build errors on unused static routines.
Fixes #174
> pkcs11: remove dead function auth_min_rw_so

- src/lib/db.c
- src/lib/key.c
- src/lib/object.c
- src/lib/object.h
- src/lib/session_ctx.c
- src/lib/tpm.c
- src/lib/tpm.h
- test/integration/test.h
- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/db.py
- tools/tpm2_pkcs11/tpm2.py
The linking mechanism made C_DestroyObject and certificate support
a nightmare.
Just make the public portion of an object a seperate and descrete object
in the db that uses only the public portion of a TPM object and can
be loaded to the null hierarchy via loadexternal.
> object: make public objects a first class citizen

- docs/P11.md
- docs/PKCS11_TOOL.md
- src/lib/db.c
- src/lib/db.h
- src/lib/encrypt.c
- src/lib/encrypt.h
- src/lib/key.c
- src/lib/object.c
- src/lib/object.h
- src/lib/session_ctx.c
- src/lib/session_ctx.h
- src/lib/sign.c
- src/lib/slot.c
- src/lib/token.c
- src/lib/token.h
- src/lib/tpm.c
- src/pkcs11.c
- test/integration/pkcs-get-mechanism.int.c
- test/integration/pkcs-keygen.int.c
- test/integration/test.h
Implement C_DestroyObject by reference counting when tobjects are in use
internally in the library across operations. If C_Destroy() occurs when
the reference count is > 1, then it should fail with
CKR_FUNCTION_FAILED. Otherwise, delete it from the token tobject list
and and remove the DB entry.
Fixes #144
> object: implement C_DestroyObject()

- src/lib/key.c
With the latest changes the MODULUS_BITS attribute was not stored in the
private tobj. This caused the sign operation to fail, if the key was
generated using the C_GenerateKeyPair Method with the following error
message:
`ERROR on line: "269" in file: "src/lib/sign.c": Signing key has no
modulus`
Fixes: 9f043bf ("object: make public objects a first class citizen")
> key.c: Store private attributes too

- src/lib/key.c
- test/integration/pkcs-keygen.int.c
- tools/tpm2_pkcs11/commandlets_keys.py
Per:
- http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/errata01/os/pkcs11-curr-v2.40-errata01-os-complete.html#_Toc441850406:
Sections:
- 2.1.2
- 2.1.3
public and private RSA key objects need:
- CKA_MODULUS
- CKA_MODULUS_BITS
- CKA_PUBLIC_EXPONENT
Ensure that all objects have them set in the tests.
Fixes: #203
> rsa: fix public and private attributes

- Makefile.am
- src/lib/object.c
- test/integration/pkcs-get-attribute-value.int.c
See Spec C_GetAttributeValue
"2.     Otherwise, if the specified value for the object is invalid (the
object does not possess such an attribute), then the ulValueLen field in
that triple is modified to hold the value CK_UNAVAILABLE_INFORMATION.
"If case 2 applies to any of the requested attributes, then the call
should return the value CKR_ATTRIBUTE_TYPE_INVALID."
> Return correct values for empty attributes in C_GetAttributeValue

- Makefile.am
- configure.ac
- lib/tpm2-pkcs11.pc.in
Apply the changes made upstream in https://github.com/tpm2-software/tpm2-tss/pull/1372 to tpm2-pkcs11:
- Use `AC_CONFIG_FILES` instead of `sed` for variable substitutions.
- Define variables for `libdir` and `includedir` in the pkg-config files so that the user can determine where the files have been installed. This is standard practice, see the [example pkg-config file](https://people.freedesktop.org/~dbn/pkg-config-guide.html#using).
> Improve pkg-config file

- Makefile.am
- configure.ac
Apply the changes from https://github.com/tpm2-software/tpm2-tss/pull/1384:
- Use `PKG_INSTALLDIR` to determine the pkg-config directory, which allows changing it with `./configure --with-pkgconfigdir`.
- Use distclean instead of clean for .pc files, since they are generated by configure since 88aac7c66e5e5e12a9100035b5ae858e6e5ad47e.
> build: use PKG_INSTALLDIR to determine pkgconfigdir

- test/integration/pkcs-login-logout.int.c
The test `test_so_state_pin_init_good()` in `pkcs-login-logout.int.c` does not log out. As a consequence, `tpm_flushcontext()` is not called and at some point the TPM memory may overflow. Thus, a call to `logout()` was added.
Additionally, a redundant line of code with no purpose was removed.
The utility function `swap_pin()` function calls `logout()` which is not obvious. This call was moved to the tests which call `swap_pin()`.
>  Tests: Add logout to test_so_state_pin_init_good to free memory on the TPM

- test/integration/scripts/create_pkcs_store.sh
With commit 9c3e6387 ("tpm2_evictcontrol: support saving ESYS_TR") in
tpm2-tools, the output of tpm2_evictcontrol was changed in a way that
the test setup script for tpm2-pkcs11 broke, as it did not parse the
output correctly.
Instead of using cut and set and hoping that the parameter is at the
correct position, we use a more robust grep.
> Fix integration tests for latest tpm2-tools

- tools/tpm2_pkcs11/tpm2.py
Upstream commit https://github.com/tpm2-software/tpm2-tools/commit/9c3e6387be57352eb7ceba289cab8dd5f82efeb9 added a key called `persistent-handle` to the YAML output of `tpm2_evictcontrol`. The old key `persistentHandle` was not removed, resulting in duplicate output, which was fixed by https://github.com/tpm2-software/tpm2-tools/commit/f68e69b93b98721fe896b4c530c5cf9dacdeb415. Therefore `tpm2_ptool` needs to be updated to the new name as well, otherwise [the CI fails](https://travis-ci.org/tpm2-software/tpm2-pkcs11/jobs/531999796#L2695).
> tpm2_ptool: update to changed output of tpm2_evictcontrol

- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/commandlets_store.py
- tools/tpm2_pkcs11/commandlets_token.py
- tools/tpm2_pkcs11/tpm2.py
According to the yaml documentation yaml.load is deprecated since PyYAML
5.1 without specifying the loader.
Since we are not doing special stuff, we can use the safe_load function
instead.
Fixes #213
> Use yaml.safe_load for importing yaml

- src/lib/general.c
- src/lib/utils.h
- test/integration/pkcs-misc.int.c
According to the standard these fields must be padded with blanks and
should not be null terminated.
Also it makes sense to check whether the supplied pointer is not null
and add a test
> Pad manufacturer id and library description and add nullpointer check

- tools/tpm2_pkcs11/commandlets_token.py
https://github.com/tpm2-software/tpm2-tools/commit/54ef8cb2f5ed1f26d9f04852456a0f437600f92a
renamed everything from 'value' to 'raw' if the value was not touched,
which broke tpm2_ptool.
Fixes #228 
> Fix breakage of tpm2_ptool due to latest tool update.

- src/lib/general.c
- src/lib/slot.c
- src/lib/token.c
- src/lib/tpm.c
- src/lib/tpm.h
This patchset retrieves the token info from the TPM and maps the result also to the slot info.
Signed-off by: Peter Huewe <peter.huewe@infineon.com>
> Retrieve Token and Slot Info from TPM

- Makefile.am
In #230 I linked the integration tests against tss2-mu. While this compiles successfully, it is not what we want: it is not the tests that require tss2-mu, but the library itself, see e.g. [`src/lib/tpm.c`](https://github.com/tpm2-software/tpm2-pkcs11/blob/8c9f31fbe73d5d0497b3b17c0f6e7666078bb715/src/lib/tpm.c#L682) or the output of `nm -D libtpm2_pkcs11.so`. Therefore link the library itself against tss2-mu, otherwise every application using the library (like the integration tests) needs to link against tss2-mu as well, which is not desired.
> build: link libtpm2_pkcs11 against tss2-mu

- lib/tpm2-pkcs11.pc.in
- `Libs` should contain the linker flags necessary to link the library, not its private dependencies.
- Since there is not header file, there is no need to add `-I` to `Cflags`.
- Add internal dependencies according to the Makefile to `Requires.private` and `Libs.private`. This is necessary for static linking.
> pkg-config: fix "Libs" and add private dependencies

- src/lib/token.c
In our current approach, the token is initialized with tpm2_ptool addtoken
command, where the userpin is mandatory.
Thus if the token is initialized, the userpin is also initialized, so the
token should report this.
This is needed e.g. for correct functionality with nss / firefox.
Fixes #235 
> Report CKF_USER_PIN_INITIALIZED in TokenInfo if initialized

- src/lib/slot.c
- src/lib/tpm.c
- src/lib/tpm.h
[This is an alternative version which does not filter the list, but might be harder to maintain]
Query the TPM whether a specified mechanism can be supported or not.
Unfortunately the mapping is not 1:1.
There might be cases where the combination of supported algorithms by
the TPM show that a mechanism is supported, but eventually cannot be
used for *certain* use cases.
(e.g. `aes` reported as supported, but `TPM2_EncryptDecrypt` is not
implemented, then we cannot use it for encrypt or decrypt).
These cases can maybe be specified/handled in more detail in
`slot_mechanism_info_get`.
This logic atleast filters out mechanism, which are definitely not
supported by the specific TPM (e.g. `sha512`).
> mechanism: Report only mechanisms supported by TPM (alternative)

- src/lib/key.c
- src/lib/tpm.c
- test/integration/pkcs-keygen.int.c
Add a handler for CKA_KEY_TYPE, this basically checks whether the key type
matches the selected mechanism.
This is done by checking whether the selected TPM algorithm matches the key type.
Fixes #168 
> tpm: Handle CKA_KEY_TYPE attribute for GenerateKeyPair

- tools/tpm2_pkcs11/utils.py
`raw_input()` has been [renamed to `input()` in Python 3](https://www.python.org/dev/peps/pep-3111/), the old `input()` from Python 2 is gone.
> tpm2_ptool: replace raw_input() by input() for Python 3

- src/lib/key.c
- test/integration/pkcs-get-attribute-value.int.c
- test/integration/pkcs-keygen.int.c
- test/integration/test.c
- test/integration/test.h
A variable with the name ck_false should have the value CK_FALSE,
not CK_TRUE!
> test: Fix true/false assignment

- src/lib/slot.c
- test/integration/pkcs-get-mechanism.int.c
This patch populates the MECHANISM_INFO structure for each of the supported
mechanisms, as a preparation to pull this information from the TPM.
The min/max keysizes were taken from the `Implementation.h` from the simulator,
for now.
Maybe RSA1k keys should be removed from the list, as e.g. TCG PTP spec lists
them as 'support for 1024-bits keys is not recommended'.
The AES Keysizes are in bytes according to the standard, not bits, so this also
fixes a bug.
The usage flags were largely derived from tables like
http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/errata01/os/pkcs11-curr-v2.40-errata01-os-complete.html#_Toc441850404
> Populate MECHANISM_INFO for supported mechanisms

- tools/tpm2_pkcs11/db.py
We need a way to track the current version of our db format.
If the format (e.g. table structure or names) change, an update path/tool
can be created based on the schema version.
Fixes #195
> Add DB schema for future upgrades

- src/lib/utils.h
`str_padded_copy` is used both for zero-terminated strings as well as fixed char arrays (blank padded). `strlen` doesn't work for arrays without zero termination and does an out-of-bounds read until it finds a null character. This triggers stack smashing protection resulting in a segfault on some systems. Using `strnlen(s,l)` is functionally equivalent and guarantees that at most l characters are consumed, avoiding a buffer over-read.
Fixes: #232
> utils: replace min(strlen(s),l) by strnlen(s,l) in str_padded_copy

- tools/tpm2_pkcs11/tpm2.py
With latest commit in tpm2_tools (b561c7d5) the tpm2_changeauth behaviour
was changed.
From the man pages the tpm2_changeauth command layout changed from
`tpm2_changeauth -C primary.ctx -P foo -p bar -c key.ctx -r new.priv`
to
`tpm2_changeauth -C primary.ctx -p foo        -c key.ctx -r new.priv bar`
Thus -P became -p and
the previous -p was removed and passed as regular argument
Fixes: #258 
> Update to latest tpm2_tools tpm2_changeauth command layout

- tools/tpm2_pkcs11/tpm2.py
This has been changed upstream in https://github.com/tpm2-software/tpm2-tools/pull/1582, cf. the currently [failing build](https://travis-ci.org/tpm2-software/tpm2-pkcs11/jobs/554728372#L2746).
> tpm2_ptool: update tpm2-tools option from -b to -a

- tools/tpm2_pkcs11/utils.py
the os.random() call for salt, when not specified, is only invoked once,
causing each call to get the same nonce. Move it to the function body
so if None, then it gets invoked will cause unique nonces per
invocation.
> tpm2_pkcs11/utils.py: hash_pass needs unique salt

- .ci/docker.run
Similar to https://github.com/tpm2-software/tpm2-tss/pull/1446, much of the CI time is spent on running the integration test suite, which is not CPU bound, so allowing more parallel jobs allows for some speedup. This reduces the CI time from about [00:18 real-time/01:12 total](https://travis-ci.org/tpm2-software/tpm2-pkcs11/builds/555571745) to about [00:09 real-time/00:33 total](https://travis-ci.org/tpm2-software/tpm2-pkcs11/builds/555982412).
> ci: don't limit the amount of parallel jobs for make check

- test/integration/scripts/create_pkcs_store.sh
- tools/tpm2_pkcs11/tpm2.py
Several tpm2-tools options changed:
-  tpm2_evictcontrol: `-a` became `-C` (tpm2-software/tpm2-tools@3c097b83)
-  tpm2_getcap : `-c` became an argument (tpm2-software/tpm2-tools@cfc2538a)
-  tpm2_encryptdecrypt: `-D` became `-d` (tpm2-software/tpm2-tools@75a86d5c2, note: the commit message is wrong)
Hence, these options have to be changed here, as well.
> Fix tools options

- test/integration/scripts/create_pkcs_store.sh
- tools/tpm2_pkcs11/commandlets_token.py
- tools/tpm2_pkcs11/tpm2.py
Some tool options changed and thus have to be changed here, too.
- tpm2_createprimary: `-o` became `-c` (tpm2-software/tpm2-tools@3939d715)
- tpm2_load: `-o` became `-c` (tpm2-software/tpm2-tools@888f63c4)
Additionally, a typo was fixed.
> Fix change of tool options

- test/integration/scripts/int-test-setup.sh
Currently the integration tests fail with
```
Traceback (most recent call last):
File "/home/jonas/tpm2-software/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 96, in __call__
handle = Tpm2.evictcontrol(ownerauth, ctx)
File "/home/jonas/tpm2-software/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2.py", line 47, in evictcontrol
handle = y['persistent-handle'] if rc == 0 else None
TypeError: 'NoneType' object is not subscriptable
'NoneType' object is not subscriptable
```
because `tpm2_evictcontrol` gives the error
```
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:116:handle_from_name() Failed to load TCTI for name "abrmd": libtss2-tcti-abrmd.so: cannot open shared object file: No such file or directory
ERROR:tcti:src/tss2-tcti/tctildr.c:417:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI …
```
> test: update TPM2TOOLS_TCTI for tss2-tctildr

- .ci/docker.run
The ocnditional checks were checking if CC == gcc, which is not valid
when:
- CC is empty, which is a comon implication for configure to choose
gcc.
- when gcc has the version number tacked onto it, like gcc-6.
Just check that CC != clang* and assume it's gcc and run a configure
without any options disabled and also perform the make distcheck to
make sure the release tarball doesn't break.
Now you'll also see errors during the build like:
../../src/lib/object.c:650:12: error: 'my_unused_func' defined but not used [-Werror=unused-function]
static int my_unused_func(void) {
^
Fixes: #211
> ci: fix build with gcc not running plain build

- test/integration/scripts/int-test-setup.sh
Fix a bug where tests would not run unless a setup script was provided.
> Test: Run tests without setup script

- src/lib/db.c
- src/lib/tpm.c
- src/lib/tpm.h
- test/integration/scripts/create_pkcs_store.sh
- test/integration/test.h
- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/commandlets_store.py
- tools/tpm2_pkcs11/commandlets_token.py
- tools/tpm2_pkcs11/db.py
- tools/tpm2_pkcs11/tpm2.py
- tools/tpm2_pkcs11/utils.py
Raw handles are not TPM MITM attack safe, however, ESYS_TR's are so
use them.
Fixes: #130
> db: use ESYS_TR instead of raw handle

- src/lib/general.c
- src/lib/slot.c
- src/lib/token.c
- src/lib/utils.h
The PKCS11 string interfaces to the user are not NULL terminated
and are padded with leading spaces. There was some redundant code
so clean it up.
> cleanups on str padding

- src/lib/slot.c
- test/integration/pkcs-misc.int.c
When the size is too small, the count ptr should also be set
to the proper size per section 5.2 of:
- http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959708
Fixes: #299
> C_GetSlots: set size on CKR_BUFFER_TOO_SMALL

- src/lib/digest.c
- src/lib/digest.h
- src/lib/sign.c
- src/lib/tpm.c
- src/lib/tpm.h
Since we don't use the tickets produced by the TPM and have no
fantastic way of exposing that feature, just do any required
hashing in SW.
Fixes: #307
> tpm: remove tpm hashing only use SW

- tools/tpm2_pkcs11/command.py
- tools/tpm2_pkcs11/commandlets_store.py
Mirror the C db code when searching for a store path by:
1. if set, just use the environment variable TPM2_PKCS11_STORE
2. if not set try:
a. does $HOME/.tpm2_pkcs11 directory exist, if so use it.
b. does /etc/tpm2_pkcs11 directory exist, if so use it.
c. A final default of the current working directory.
Update the help output to reflect this.
Also do NOT automatically mkdir paths, as we don't want to willy nilly
create directories if they don't exist.
> tpm2_ptool: make --path optional work correctly

- src/lib/digest.c
- src/lib/digest.h
- src/lib/general.c
- src/lib/sign.c
- src/lib/slot.c
- src/lib/token.c
- src/lib/token.h
- src/lib/tpm.c
- src/lib/tpm.h
- src/lib/utils.h
- test/integration/pkcs-get-mechanism.int.c
Various code paths ask the tpm for a list of supported mechanisms. Going
to the TPM is slow, and this information never changes. Cache the
results so we only pay for the slowness once and refactor the code paths
so it calls into the cache layer.
This also updates all the callers to ask the TPM for supported
algorithms and keysizes rather than keeping lists hardcoded to
the simualtor.
Fixes: #310
> token: refactor and cache mechanism query

- test/integration/scripts/create_pkcs_store.sh
Running the integration test outside Travis CI fails because `create_pkcs_store.sh` relies on a hardcoded `/workspace` build directory. Specify locations relative to the current build directory `$PWD` instead to make the tests portable.
> test: use relative path to determine location of libtpm2_pkcs11

- .travis.yml
- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/utils.py
Figured out the issue, for details see commit messages and https://github.com/etingof/pyasn1/issues/185
> re-enable python 3 testing

- configure.ac
- docs/BUILDING.md
- test/integration/scripts/int-test-setup.sh
Propagate two changes to the build system already implemented in other tpm2-software projects:
- [Replace `netstat` by `ss`](https://github.com/tpm2-software/tpm2-tss/pull/1234) since the former is deprecated.
- [Add `-O2` required for fortification and use `AX_ADD_FORTIFY_SOURCE`](https://github.com/tpm2-software/tpm2-tools/pull/1590).
> build: replace netstat by ss, add -O2 and use AX_ADD_FORTIFY_SOURCE

- tools/tpm2_pkcs11/commandlets_keys.py
pkcs11-tool requests CKA_VALUE for secret objects. Since this is a
common tool and client, just placate it with an empty CKA_VALUE field.
Example:
pkcs11-tool --module /home/wcrobert/workspace/tpm2-pkcs11/src/.libs/libtpm2_pkcs11.so --login --label label --list-objects
Fixes Error:
Secret Key Object; AES
warning: PKCS11 function C_GetAttributeValue(VALUE) failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x12)
label:      3
ID:         31363634663637356533646332376632
Usage:      encrypt, decrypt
Fixes: #326
> pkcs11-tool: fix CKA_VALUE request for aes key

- src/lib/attrs.c
- src/lib/object.c
- tools/tpm2_pkcs11/objects.py
Refactoring the attribute handling resulted in the loss of CKA_SENSITIVE
attribute. Correct this by adding it in for all PKCS11 Private Keys as
well as PKCS11 Secret Keys.
Fixes: #347
> attributes: add CKA_SENSITIVE

- src/lib/general.c
- test/integration/pkcs-misc.int.c
The previous commit 4313073a420c40fb99de4c0c078febd8627e2901 exposed some problems of the [`parse_lib_version`](https://github.com/tpm2-software/tpm2-pkcs11/blob/4313073a420c40fb99de4c0c078febd8627e2901/src/lib/general.c#L33) function because its short commit id, which is [used as the `PACKAGE_VERSION`](https://github.com/tpm2-software/tpm2-pkcs11/blob/4313073a420c40fb99de4c0c078febd8627e2901/configure.ac#L29), is a decimal number > `UINT8_MAX`. This results in a [failing integration test](https://travis-ci.org/tpm2-software/tpm2-pkcs11/jobs/623306231#L2829) due to a [wrong comparison operator](https://github.com/tpm2-software/tpm2-pkcs11/blob/4313073a420c40fb99de4c0c078febd8627e2901/src/lib/general.c#L61) in the assertions, which should be `<=` instead of `>`.
Unify the code of …
> general: fix and unify parse_lib_version()

- Makefile.am
Explicitly calling `dlopen()` is no longer necessary after the switch to tss2-tctildr.
> build: remove linking against libdl

- Makefile.am
- configure.ac
- test/integration/scripts/int-test-setup.sh
- test/integration/tls-tests.sh
Add files necessary to run integration tests from a tarball created by `make dist`, and setup running `make distcheck` with tests enabled to catch such issues in the CI.
>  build: add necessary files for integration tests to distribution

- .ci/docker.run
- .ci/download-deps.sh
- .travis.yml
- Makefile.am
- configure.ac
- docs/BUILDING.md
- src/lib/db.c
- src/lib/db.h
- src/lib/emitter.c
- src/lib/emitter.h
- src/lib/slot.c
- src/lib/slot.h
- src/lib/token.c
- src/lib/token.h
- src/lib/tpm.c
- src/lib/tpm.h
- src/pkcs11.c
- test/integration/pkcs11-tool-init.sh.nosetup
- test/integration/test.h
- tools/setup.py
- tools/tpm2_pkcs11/__init__.py
- tools/tpm2_pkcs11/commandlets_store.py
- tools/tpm2_pkcs11/db.py
- tools/tpm2_ptool
- Depends on CI build changes:
- https://github.com/tpm2-software/tpm2-software-container/pull/22
Initial code for supporting C_InitToken, on 1 of three states:
1. db found with primary object configured, use that.
2. no db found, use PC WG Spec SRK if present at address 0x81000001
3. no db found, create a persistent key at the first persistent slot.
**This contains a schema bump and upgrades the DB**
**Backup your db**
I would recommend, since this is the first upgrade schema code, to manually backup your db.
Backup instructions can be found here:
- https://stackoverflow.com/questions/25675314/how-to-backup-sqlite-database
> C init token support

- src/lib/db.c
- tools/tpm2_pkcs11/db.py
Fixes errors like:
ERROR: unrecognized token: "0x00FFFFFF"
Fixes: #379
> db: fix sqlite3 unrecognized hex scalar token

- .gitignore
- Makefile.am
- docs/INSTALL.md
- src/lib/attrs.c
- src/lib/attrs.h
- src/lib/encrypt.c
- src/lib/encrypt.h
- src/lib/object.c
- src/lib/object.h
- src/lib/openssl_compat.c
- src/lib/openssl_compat.h
- src/lib/token.c
- src/lib/tpm.c
- src/lib/tpm.h
- src/pkcs11.c
- test/integration/PKCS11JavaTests.java
- test/integration/pkcs-keygen.int.c
- test/integration/pkcs11-javarunner.sh.java
- test/integration/scripts/create_pkcs_store.sh
This creates basic support for RSA public key crypto for algorithm
RSA/ECB/RSAPKCS1.5 padding in Java. Other schemes may work, but are
untested. Test machines must have the hamcrest and junit JAR files on
their CLASSPATH.
Fixes: #341
> C_CreateObject: minimal RSA Java support

- configure.ac
- test/integration/PKCS11JavaTests.java
In Java >=9, the PKCS#11 provider needs to be configured as follows:
```
String pkcs11Config = "--name = TPM2\nlibrary = " + libPath;
PROV = Security.getProvider("SunPKCS11");
PROV = PROV.configure(pkcs11Config);
```
The `sun.security.pkcs11.SunPKCS11` class is not user-accessible any more, trying to instantiate it leads to a "package sun.security.pkcs11 is not visible" compilation error.
In Java <= 8, the `Provider.configure()` method does not exist, the configuration needs to be supplied to the class constructor instead.
To support all Java versions, check if `Provider.configure()` is available and fall back to the old code in case it is not. To avoid compile-time "symbol not found" errors due to missing/inaccessible methods and classes, we need to use introspection to do the resolution …
>  PKCS11JavaTests: Java >= 9 compatibility

- src/lib/object.c
- src/lib/session_ctx.c
- src/lib/token.c
- src/lib/token.h
- test/integration/pkcs-login-logout.int.c
Verify that C_CloseAllSessions() causes a logout of the token to
occur.
Fixes: #127
> test: verify C_CloseAllSessions implicitly logs out

- tools/tpm2_pkcs11/commandlets_keys.py
This PR comprises two changes to tpm2_ptool objmod that fix the type check when setting a new value to an attribute, and also allow to add new attributes to an object, rather than just changing existing values.
> tpm2_ptool: objmod fixes

- src/lib/sign.c
- src/lib/tpm.c
- src/lib/utils.c
**Update**
Just support CKM_RSA_X509 via C_Sign()
**Old outdated, dumb idea below**
Assymetric keypairs are represented by PKCS11/TPM internals as 2
objects. The private key handle contains the public and private portion
of the RSA object and the public handle contains only the public
portion. The TPM cannot distinguish the private key case for calls
performing RSA Encrypt or Decrypt, and thus default to their proper
keys. RSA Decrypt uses the private key, and RSA Encrypt uses the public
key. This can cause issues where a call is made to C_Encrypt with a
private key object. The code was calling TPM2_RSA_Encrypt, which
performs the RSA operation using the public key, thus calls using public
keys loaded into OSSL to decrypt with the public key (perform RSA
Encrypt) will fail. Below is …
> tpm: support raw RSA crypto in C_Sign

- src/lib/token.h
The package build started failing with current gcc10 because of multiple definition of `config`. In the end, it turned out that this global variable is not used in the code at all so I think the correct approach will be to remove it altogether as in the attached commit.
https://bugzilla.redhat.com/show_bug.cgi?id=1796383
> Drop unused variable which is causing the build to fail with current gcc10

- src/lib/encrypt.c
- src/lib/key.c
- src/lib/object.c
- src/lib/object.h
- src/lib/session_ctx.c
- src/lib/sign.c
- src/lib/token.c
- src/lib/tpm.c
The index field implies that it's an index into a list, which in some
cases it is. However, the value may not always be in the index, as the
list can contain holes, for instance if obect at list index 2 is
deleted, the list would have a hole.
The index is really the object handle, so call it that. And while the
internal list is kept in order so holes can be filled in, and the handle
assigned an index in the hole, it's still just a handle.
The spec does discuss that the handle will be valid under three
conditions:
1. The session continues to exist that the object was discovered on.
2. The object continues to exist.
3. The object is still accessible.
The current logic does have some issues in that:
1. The handle is not invalidated if the session is closed.
2. A logout will cause the object …
> tobject: change field index to handle

- src/lib/attrs.c
- src/lib/digest.c
- src/lib/digest.h
- src/lib/emitter.c
- src/lib/encrypt.c
- src/lib/encrypt.h
- src/lib/mech.c
- src/lib/mech.h
- src/lib/mutex.h
- src/lib/object.c
- src/lib/object.h
- src/lib/sign.c
- src/lib/slot.c
- src/lib/token.c
- src/lib/token.h
- src/lib/tpm.c
- src/lib/tpm.h
- src/lib/typed_memory.c
- src/lib/utils.c
- src/lib/utils.h
- test/integration/pkcs-get-mechanism.int.c
- test/integration/pkcs-sign-verify.int.c
Mechanisms have long been a sore point. The multiple switches and locations that had to make decisions on CKM_* values meant that adding in new algorithms as folks needed support was quite difficult. Move away from a decentralized chaotic mess and into a common table handler, much like the attribute code. While the table and idoms aren't as clean as I hoped for, it's a vast improvement in reducing CKM_ calls.
TODO: Utils needs some more house keeping.
Fixes: #404
> mechanism refactor

- Makefile.am
- test/integration/pkcs11-dbup.sh.nosetup
This works even if running the test suite from a release tarball. If cloning fails e.g. because the software is build without internet access, skip the test instead of failing the test suite.
Fixes: #410
> test/pkcs11-dbup: clone from GitHub project repository

- docs/BUILDING.md
- test/integration/pkcs-get-mechanism.int.c
SHA-512 is supported by the IBM TPM simulator since version 1332, update the CI build environment instead, see tpm2-software/tpm2-software-container#26, to make the test pass.
> test/pkcs-get-mechanism: re-add CFK_HW to CKM_SHA512_RSA_PKCS flags

- src/lib/db.c
Since commit 548c65c384e1b6628974e9a5eebf9fe7e9a9b488 GCC >= 7 produces several warnings of the form
```
src/lib/db.c: In function ‘db_new.constprop’:
src/lib/db.c:1504:37: error: ‘%s’ directive output may be truncated writing 5 bytes into a region of size between 1 and 4096 [-Werror=format-truncation=]
1504 |     snprintf(lockpath, PATH_MAX, "%s%s", path, ".lock");
|                                     ^~         ~~~~~~~
```
> db: avoid -Werror=format-truncation with GCC >= 7

- src/lib/sign.c
The wrong type, introduced during refactoring in d80809ac3b8267f346f90bc3c73275bd8c66456e, causes errors for 32 bit builds of the form
```
src/lib/sign.c: In function 'sign_final_ex':
src/lib/sign.c:231:83: error: passing argument 4 of 'digest_final_op' from incompatible pointer type [-Werror=incompatible-pointer-types]
231 |         rv = digest_final_op(ctx, opdata->digest_opdata, (CK_BYTE_PTR)digest_buf, &hash_len);
|                                                                                   ^~~~~~~~~
|                                                                                   |
|                                                                                   size_t * {aka unsigned int *}
In file included from src/lib/sign.c:9:
src/lib/digest.h:35:107: note: expected …
```
> sign: fix hash_len type for 32 bit compilation

- Makefile.am
- test/integration/openssl.sh
The release tarball for the current [release candiate](https://github.com/tpm2-software/tpm2-pkcs11/releases/tag/1.1.0-RC0) appears to have been build without `--enable-integration`. This means the integration test suite cannot be run because some required scripts are distributed depending on the state of `ENABLE_INTEGRATION`.  Make sure that `EXTRA_DIST` is independent of the configuration options to avoid such problems in the future. Additionally there are two leftover files that `make distcheck` may complain about, make sure to remove these.
> build: always distribute test files

- test/integration/pkcs11-dbup.sh.nosetup
When running the test suite from a release tarball, using a git clone requires autoconf-archive to be installed for the Autconf bootstrap process. Replacing this with an already bootstrapped release tarball for version 1.0 changes the required packages from git/autoconf-archive to wget/tar which are more widely available. Additionally pinning the checksum of the tarball reduces the risk of downloading and running code from the Internet.
> test/pkcs11-dbup: use release tarball instead of git clone

- test/unit/test_attr.c
Fix:
libtool: link: gcc -I./src -I./src/lib -Wall -Wextra -Werror -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Wstrict-overflow=5 -O2 -fPIC -fPIE -pthread -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -pie -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -o test/unit/test_attr test/unit/test_attr-test_attr.o  -lcmocka …
> test: fix unitialized variable warnings

- src/lib/session_ctx.h
- src/lib/sign.c
- src/lib/sign.h
- src/lib/ssl_util.c
- src/lib/ssl_util.h
- src/pkcs11.c
- test/integration/PKCS11JavaTests.java
Implement C_VerifyRecover API. Known to work with RSA mechanism
CKM_RSA_PKCS as used by the Java PKCS11 Provider implementation.
Fixes: #383
> pkcs11: Implement C_VerifyRecovery

- tools/tpm2_pkcs11/commandlets_token.py
Mark key log-level as deprecated and print a warning.
The C code was ignoring it anyways, so their isn't much todo.
Fixes: #432
> tpm2_ptool config: drop key log-level

- tools/tpm2_pkcs11/command.py
I accidentally missed these LGTM Python warnings when I merged PR #436,
so fix them.
See:
- https://lgtm.com/projects/g/tpm2-software/tpm2-pkcs11/rev/pr-670ec0eda659019041aa7246b9a1b86860526474
- https://lgtm.com/rules/6780080/
> tpm2_ptool: fix LGTM py/catch-base-exception

- .ci/docker.run
- CHANGELOG.md
- Makefile.am
- configure.ac
Use autoconf to check for Python version >= 3.7 when enabling
integration tests and automatically pass that version into the
PYTHON_INTERPRETER variable in the automake check ENV.
> configure: check for python >= 3.7

- configure.ac
- src/lib/tpm.c
Latest tpm2-tss master includes an ABI break for ESYS that affects this project in the Esys_LoadExternal() call.
See https://github.com/tpm2-software/tpm2-tss/pull/1531 for details.
Evidence that this PR works on Esys >= 3.0 can be found here: https://travis-ci.org/github/AndreasFuchsSIT/tpm2-pkcs11/builds/663011856?utm_source=github_status&utm_medium=notification
(Note that the failed jobs there originate from the pkcs11-tool problems)
> ESYS: Implement ESYS 3.0 ABI break

- .ci/download-deps.sh
- .travis.yml
- Makefile.am
- configure.ac
- src/lib/backend.c
- src/lib/backend.h
- src/lib/backend_esysdb.c
- src/lib/backend_esysdb.h
- src/lib/backend_fapi.c
- src/lib/backend_fapi.h
- src/lib/db.c
- src/lib/general.c
- src/lib/key.c
- src/lib/object.c
- src/lib/object.h
- src/lib/session_ctx.c
- src/lib/slot.c
- src/lib/token.c
- src/lib/token.h
- src/lib/tpm.c
- test/integration/pkcs11-tool-init.sh.nosetup
- test/integration/scripts/int-test-funcs.sh
- test/integration/scripts/int-test-setup.sh
The current status is as follows:
- SO-seal is created in FAPI-store
- USR-seal is created in FAPI-store
- tobjects are part of so-seal appdata
- tokens of SQLite and FAPI are concatenated (so both work in parallel)
- test pkcs11-tool-init{-fapi} uses FAPI
TODOs:
- emptytoken comes from db.c instead of token.c
- Somewhat hacky concatenation (dep: emptytoken)
- pobjects are a bit hacky (need to be made Flushable for FAPI)
- other tests need to learn about FAPI; tpm2_ptool or something else ?
> FAPI backend

- .travis.yml
- test/integration/pkcs11-tool-init.sh.nosetup
Add tests for listing and reading objects as well as signing (verified using openssl).
This should trigger a bug in CI that I cannot reproduce locally.
> Test: Extend pkcs11-tool tests

- test/integration/fixtures/client.cnf
- test/integration/nss-tests.sh
- test/integration/scripts/helpers.sh
- test/integration/tls-tests.sh
Make sure all test tokens can be unlocked with matching PINs, and
propagate exit code of spawned process from expect.
Fixes: #444
> test: fix expect script for NSS pinentry

- src/lib/token.c
- test/integration/pkcs11-tool-init.sh.nosetup
This adds a regression test that deleting objects via pkcs11-tool,
specifically the private RSA object followed by the Public RSA object,
works.
Fixes: #399
> test: add regression test for delete objects

- src/lib/backend.c
- src/lib/session_ctx.c
Fix:
tpm2pkcs11-tool --slot-index=0 --login --pin="myuserpin" --label="myrsakey" --keypairgen
Using slot with index 0 (0x1)
Segmentation fault (core dumped)
Caused by seal object's private and public twist blobs being NULL and
where twist_len was called and dereferences NULL. This occurs when a
token is initialized but a userpin is not set. This condition should
return CKR_USER_PIN_NOT_INITIALIZED.
> C_Login: fix segfault on no userpin

- .ci/docker.run
- src/lib/attrs.c
- src/lib/backend_fapi.c
- src/lib/emitter.c
- src/lib/general.c
- src/lib/mech.c
- src/lib/object.c
- src/lib/tpm.c
- src/lib/twist.c
- src/lib/typed_memory.c
- src/lib/utils.c
- src/lib/utils.h
Just to help prevent overflows in the code base, use the builtin arithmetic routines that detect overflow conditions.
> use safe arithmetic

- test/integration/scripts/int-test-funcs.sh
fapi-config needs ek_cert_less option set to work with latest fapi master branch.
This mirrors this PR from the tools: https://github.com/tpm2-software/tpm2-tools/pull/1969
> Test/FAPI: Fix fapi-config

- Makefile-fuzz.am
- configure.ac
- test.mk
- test/fake-tpm/wrap_tpm.h
- test/fuzz/init-token.fuzz.c
- Fuzz a PKCS11 interface parameter: C_InitToken SOPIN argument.
- Disable -jobs, it was stomping on log files and causing output to be missed
- Add a fuzzing flags option to configure --with-fuzzing-flags, default it to the timeout of 30s.
> enable more fuzz testing

- src/lib/backend.c
- src/lib/backend.h
- src/lib/backend_esysdb.c
- src/lib/backend_esysdb.h
- src/lib/backend_fapi.c
- src/lib/backend_fapi.h
- src/lib/db.c
- src/lib/session_ctx.c
- src/lib/token.c
- src/lib/token.h
- test/integration/pkcs11-tool-init.sh.nosetup
Decouple esysdb and fapi backend by enabling the union in struct token.
Moving the unsealing into the backend.
Refactor changeauth to be a backend-function.
Implement changeauth for FAPI backend.
build ontop of #493
> FAPI: Decoupling for esysdb & implement changeauth

- src/lib/backend.c
- src/lib/backend_fapi.c
- src/lib/db.c
- src/lib/object.c
- test/integration/p11-tool.sh.nosetup
- Unify the numberspace of tok->id between esysdb and fapi
- Move the empty token creation out of db into backend
- Add tests for multiple fapi tokens (makes used of the previous changes)
> Refactoring token ids and empty tokens plus more fapi testing

- test/integration/pkcs-get-mechanism.int.c
The freshly released ibmswtpm2 version 1628 increases the maximum key
size to 3072 bits, leading to a test failure:
```
[  ERROR   ] --- 0xc00 != 0x800
[   LINE   ] --- test/integration/pkcs-get-mechanism.int.c:151: error: Failure!
[  FAILED  ] test_get_mechanism_info_good
```
Accept the previous key size of 2048 bits as well for backwards compatibility with older versions of the simulator.
> test/pkcs-get-mechanism: allow a maximum key size of 3072 bits

- .ci/travis.run
latest tag was dropped in dockerhub, but it was pointing to what is
now 16.04.
> ci: switch latest to ubuntu-16.04

- test/integration/pkcs11-dbup.sh.nosetup
Commit 260c84e3e9a1f44b09b690933e16900459739772 fixed compilation with GCC 10, but is only available in tpm2-pkcs11 >= 1.1.0. To run the database upgrade test with GCC 10, the fix must be applied to the (otherwise EOL) version 1.0 as well. Since it is tiny, use sed instead of applying a proper patch for greater portability.
> test/pkcs11-dbup: backport GCC 10 compilation fix to tpm2-pkcs11 1.0

- src/lib/attrs.c
- src/lib/attrs.h
- src/lib/object.c
- src/lib/session_ctx.c
- test/integration/pkcs-keygen.int.c
- test/integration/pkcs11-tool-init.sh.nosetup
- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/commandlets_token.py
Support storing secrets in the DB wrapped with the token wrapping key.
Since the wrapping key can unwrap all object authorizations, using the
TPM seal interface adds nothing. If you have the wrapping key, or can
brute force it, you can use the object. An object with a sealed value
means you can also release the secret. Also, a downside when using the
TPM for sealing is speed and the data cannot be bigger than 128 bytes.
Using the token wrapping key has none of these limitations.
Note: Only CKA_PRIVATE CK_TRUE objects are supported. Since the library
can make no guarentees about the attributes, an accidental or malicious
change to the CKA_PRIVATE value from CK_TRUE to CK_FALSE could cause
the plaintext value to be persisted to the store. Thus *ONLY* support
CKA_PRIVATE CKA_TRUE CKO_DATA …
> C_CreateObject: Support CKO_DATA object

- Makefile-integration.am
- src/lib/backend_esysdb.c
- src/lib/token.c
- src/lib/tpm.c
- src/lib/tpm.h
- test/integration/pkcs-lockout.int.c
Write a test to verify that DA lockout occurs after 3 bad pin attempts
and that the return code is CKR_PIN_LOCKED.
Note: this expects DA configuration to be 3, which is what the simulator
is configured for.
> test: verify that DA lockout occurs

- CHANGELOG.md
- src/lib/attrs.c
- src/lib/attrs.h
- src/lib/object.c
- src/lib/session_ctx.c
- src/lib/typed_memory.c
- src/lib/typed_memory.h
- test/integration/pkcs-keygen.int.c
- test/integration/pkcs11-tool-init.sh.nosetup
Support storing secrets in the DB wrapped with the token wrapping key.
Since the wrapping key can unwrap all object authorizations, using the
TPM seal interface adds nothing. If you have the wrapping key, or can
brute force it, you can use the object. An object with a sealed value
means you can also release the secret. Also, a downside when using the
TPM for sealing is speed and the data cannot be bigger than 128 bytes.
Using the token wrapping key has none of these limitations.
Note: Only CKA_PRIVATE CK_TRUE objects are supported. Since the library
can make no guarentees about the attributes, an accidental or malicious
change to the CKA_PRIVATE value from CK_TRUE to CK_FALSE could cause
the plaintext value to be persisted to the store. Thus *ONLY* support
CKA_PRIVATE CKA_TRUE CKO_DATA …
> [BACKPORT] C_CreateObject: Support CKO_DATA object

- .ci/download-deps.sh
- Makefile-integration.am
- configure.ac
- src/lib/utils.c
- test/integration/fixtures/tss2engine.cnf
- test/integration/ptool-link.sh.nosetup
- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/tpm2.py
- tools/tpm2_pkcs11/utils.py
Allow existing tpm2tss-genkey generated keys to be added into a token
under very specific limitations that the token's associated pobject
and tpm2tss-genkey key parent must be the same primary object.
Example:
tpm2 createprimary -c primary.ctx
tpm2 evictcontrol -c primary.ctx 0x81000003
tpm2tss-genkey -a rsa -s 2048 -P 0x81000003 tss-rsa.key
tpm2_ptool init --primary-handle 0x81000003 --path=~/tmp
action: Added
id: 4
tpm2_ptool addtoken --pid=4 --sopin=mysopin --userpin=myuserpin --label=linktoken --path=~/tmp
tpm2_ptool link --label=linktoken --userpin=myuserpin --path=/home/wcrobert/tmp /home/wcrobert/workspace/tpm2-tss-engine/tss-rsa.key
Follow on work to support tpm2tss-genkey with transient EC parents will
be next.
Progresses: #485
Signed-off-by: William Roberts …
> tpm2_ptool: add link cmd for tss keygen key

- test/integration/pkcs11-dbup.sh.nosetup
Ensure that post schema update that not only the db reports the
increased schema, but that a key still works, to make sure one didn't
bork anything along the way.
> test: do operation with key after shcmea update

- Makefile.am
- configure.ac
configure option --enable-asan depends on the tests properly setting up
the ASAN environment via helpers.sh. That depends on the ASAN_ENABLED
environment variable set to true.
> configure: fix --enable-asan env variable

- docs/INITIALIZING.md
- docs/INTEROPERABILITY.md
- src/lib/backend_esysdb.c
- src/lib/db.c
- src/lib/db.h
- src/lib/emitter.c
- src/lib/emitter.h
- src/lib/mech.h
- src/lib/parser.c
- src/lib/parser.h
- src/lib/token.c
- src/lib/token.h
- src/lib/tpm.c
- src/lib/tpm.h
- test/fuzz/db-token-label.fuzz32.c
- test/integration/ptool-link.sh.nosetup
- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/commandlets_store.py
- tools/tpm2_pkcs11/commandlets_token.py
- tools/tpm2_pkcs11/db.py
- tools/tpm2_pkcs11/tpm2.py
- tools/tpm2_pkcs11/utils.py
This bumps the DB version to 4.
Invocations of plain tpm2tss-keygen result in a transient primary
object. Add support for the libraries and tooling to support tokens
with transient primary objects so existing tpm2tss-keygen generated
keys can be linked into a token. In theory one could make a compatible
primary object persistent, but this will provide a simple mechanism
and remove all requirements of non-volatile memory.
> pkcs11: transient pobjects for tss2-keygen compat

- src/lib/ssl_util.c
Fixes:
src/lib/ssl_util.c: In function ‘ssl_util_verify_recover’:
src/lib/ssl_util.c:555:54: error: passing argument 3 of ‘EVP_PKEY_verify_recover’ from incompatible pointer type [-Werror=incompatible-pointer-types]
int rc = EVP_PKEY_verify_recover(pkey_ctx, data, data_len,
^~~~~~~~
In file included from src/lib/ssl_util.c:9:
/usr/include/openssl/evp.h:1393:58: note: expected ‘size_t *’ {aka ‘unsigned int *’} but argument is of type ‘CK_ULONG_PT
’ {aka ‘long unsigned int *’}
unsigned char *rout, size_t *routlen,
Fixes: #527
> lib: fix argument to EVP_PKEY_verify_recover

- .ci/download-deps.sh
- docs/INTEROPERABILITY.md
- src/lib/token.c
- src/lib/tpm.c
- test/integration/ptool-link.sh.nosetup
- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/commandlets_store.py
- tools/tpm2_pkcs11/tpm2.py
Support:
- tpm2_createprimary transient objects for two template friendly names
- linking in tpm2_create key blobs.
> interoperability: support linking in tpm2_create objects

- tools/setup.py
Fixes:
File "/tmp/pip-req-build-5k2d9765/setup.py", line 7, in <module>
with open(readme, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-5k2d9765/../docs/README.md'
That file won't be available in a temp build dir, so just hand-jam the
long description. The README file was too verbose anyways.
> tpm2_ptool: fix setup

- tools/setup.py
fix typo in long description of setup.py
> setup.py: fix typo in long description

- .ci/docker.run
- CHANGELOG.md
- Makefile-integration.am
- Makefile.am
- configure.ac
- src/lib/backend_fapi.c
- src/lib/config.h.in
- src/lib/token.h
- test/integration/scripts/int-test-setup.sh
Don't require that FAPI is installed by default and auto-detect it.
However, keep the requirement in the CI build so nothing unknowingly
breaks.
Fixes: #538
> configure: autodetect if FAPI is enabled

- src/lib/db.c
- src/lib/session_ctx.c
- src/lib/token.c
- src/lib/token.h
- test/integration/pkcs-initialize-finalize.int.c
- test/integration/pkcs-login-logout.int.c
A command like:
pkcs11-tool --module /usr/lib/libtpm2_pkcs11.so --init-token --label tpmhsm --so-pin foo --pin bar
Will cause a C_Login even because --pin is specified. However, C_InitPIN
has not been called to initialize the userpin. This causes a NPD when
trying to load the user sealobjects public and private blobs.
Their's also a bug when a token is inserted with the same name and UNIQUE db constraint fails. This causes the cleanup code to free a mutex that is currently being held. Fix that too.
Add a check to make sure the label doesn't have an embedded null byte, per the spec.
Add tests for everything
Fixes: #563
> various fixes

- src/lib/token.c
- src/lib/token.h
token_fre_ex is not needed, revert back to just token_free.
> token: remove non-needed routine

- configure.ac
tpm2_ptool depends on the following tools:
- tpm2_createprimary
- tpm2_create
- tpm2_evictcontrol
- tpm2_readpublic
- tpm2_load
- tpm2_loadexternal
- tpm2_unseal
- tpm2_encryptdecrypt
- tpm2_sign
- tpm2_getcap
- tpm2_import
- tpm2_changeauth
Add checks in configure to make sure they exist.
Fixes: #562 
> [BACKPORT] configure: add tpm2-tools checks for tpm2_ptool

- .ci/download-deps.sh
tpm2-tss: 3.0
tpm2-abrmd: 2.3.3
tpm2-tools: 4.0
tpm2-tss-engine: v1.0.1
Fixes: #548
> ci: set stable versions

- configure.ac
This typo leads to the (otherwise harmless) [error message](https://travis-ci.org/github/tpm2-software/tpm2-pkcs11/jobs/718688257#L3761)
```
checking for TSS2_FAPI... yes
../configure: line 14383: ]: command not found
checking for CMOCKA... yes
```
> configure: remove superfluous closing bracket from $have_fapi test

- src/lib/mech.c
This has two main patches:
1. Fix unwritten index 0 in C_GetMechanismInfo, which was causing applications to try and ask for information on a potential invalid mechanism.
2. Fix some flags causing spurious error messages about not supported mechanisms in C_GetMechanismInfo.
Fixes: #555
> Fix ecc key errors

- docs/README.md
The absolute links ensure that they work also when followed from the README file in the root directory.
Currently, following links from the README presented in the main page results in 404s, because they link to documents in the same directory, i.e. in the root.
> Explicitly linking to docs directory

- .ci/docker.run
- Makefile-unit.am
- Makefile.am
- configure.ac
- src/lib/config.h.in
- src/lib/db.c
- src/lib/db.h
- src/lib/debug.h
- src/lib/object.c
- src/lib/object.h
- src/lib/parser.h
- src/lib/ssl_util.h
- src/lib/tpm.c
- src/lib/twist.c
- src/lib/utils.h
- test/fuzz/yaml-parser.fuzz.c
- test/integration/test.h
- test/unit/test_db.c
Add some additional db tests to cover error paths to increase code
coverage.
These tests specifically target:
- _get_blob
- get_blob
- get_blob_null
- db_tobject_new
> db: code cov increase

- .ci/docker.run
The main build uses `--disable-hardening` in `$config_flags`, which avoids catching compiler warnings e.g. for unused variables because `-Werror` is not set. Enable compiling the tests during the "pure" distcheck run, but empty `TESTS` to avoid running the entire test suite another time.
CI failures are expected until 583f5773ed4f0e966217be35e7ab864724481a83 is merged so that the `CK_RV rv` variables are no longer unused, see #597 for the corresponding error message. My personal Travis CI shows a successful run of this commit on top of the 1.4.0 release at https://travis-ci.org/github/diabonas/tpm2-pkcs11/builds/723903343.
> ci: enable building unit and integration tests during distcheck

- tools/tpm2_pkcs11/commandlets_store.py
- tools/tpm2_pkcs11/tpm2.py
According to the [TCG TPM v2.0 Provisioning Guidance](https://trustedcomputinggroup.org/wp-content/uploads/TCG-TPM-v2.0-Provisioning-Guidance-Published-v1r1.pdf#page=29), the SRK should be stored at 0x81000001. Check whether this handle is available and store the primary key object there during `tpm2_ptool init`, falling back to the current behaviour of looking for the first available handle if it is already occupied.
> tpm2_ptool: prefer 0x81000001 to store primary key objects

- src/lib/ssl_util.c
- test/integration/pkcs-keygen.int.c
When calling EVP_PKEY_encrypt, let OpenSSL determine if the buffer
length is too small. Per the manpage, the required minimum output buffer
sizes are quite nuanced, and I quote from:
- https://www.openssl.org/docs/man1.1.1/man3/RSA_public_encrypt.html
"to must point to a memory section large enough to hold the maximal possible decrypted data (which is equal to RSA_size(rsa) for RSA_NO_PADDING, RSA_size(rsa) - 11 for the PKCS #1 v1.5 based padding modes and RSA_size(rsa) - 42 for RSA_PKCS1_OAEP_PADDING). padding is the padding mode that was used to encrypt the data. to and from may overlap."
> ssl_util: let openssl verify output buffer length

- Makefile-integration.am
- configure.ac
- src/lib/ssl_util.c
- src/lib/ssl_util.h
- test/integration/PKCS11JavaTests.java
- test/integration/openssl.sh
- test/integration/pkcs-crypt.int.c
- test/integration/python-pkcs11.sh
- Fix issue #567, C_Decrypt wasn't doing the 5.2 style returns for public keys when getting output buffer size, so fix it.
- Add a C integration test for that bug
- Add a python-pkcs11 integration test for that bug
Fixes: #567
> python-pkcs11: fix 5.2 style returns and add tests

- .ci/docker-prelude.sh
- Makefile-integration.am
- configure.ac
- docs/BUILDING.md
- docs/INITIALIZING.md
- test/integration/pkcs-get-mechanism.int.c
- test/integration/scripts/int-test-funcs.sh
- test/integration/scripts/int-test-setup.sh
tpm2-tss supports the [swtpm](https://github.com/stefanberger/swtpm) TPM simulator since version 3.0.0. One small change in [` test/integration/pkcs-get-mechanism.int.c`](https://github.com/tpm2-software/tpm2-pkcs11/compare/master...diabonas:add-swtpm?expand=1#diff-c9fd97e9e9ba72d316720e723fcea5c104ebb2e8b3810e49c401d8045725769a) was necessary because swtpm supports more elliptic curves than ibmswtpm, other than that everything worked out of the box.
Support for ibmswtpm (aka `tpm_server`) is kept for backwards compatibility, but swtpm is preferred if it is available. Since the Docker images come with swtpm preinstalled, this means that this PR switches CI testing from ibmswtpm to swtpm as well.
> test: add support for swtpm simulator

- src/lib/digest.c
- src/lib/mech.c
- src/lib/mech.h
- src/lib/tpm.c
- test/integration/PKCS11JavaTests.java
- test/integration/pkcs-crypt.int.c
- test/integration/pkcs-keygen.int.c
- test/integration/pkcs-misc.int.c
- test/integration/pkcs11-tool.sh
Fix a condition on 5.2 style returns in C_Digest where the output buffer
is NULL and the digestlen is greater than the expected hashlen and the
5.2 style reurn handling code wasn't being invoked. Update the tests to
cover this conditions.
This bug was discovered when running:
tpm2pkcs11-tool --test --login
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:221:Fapi_List_Finish() FAPI not provisioned.
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:81:Fapi_List() ErrorCode (0x00060034) Entities_List
ERROR: Listing FAPI token objects failed.
Using slot 0 with a present token (0x1)
Logging in to "label".
Please enter User PIN:
C_SeedRandom() and C_GenerateRandom():
seems to be OK
Digests:
all 4 digest functions seem to work
ERROR: Mechanism not supported, got: 0x210
SHA-1: OK
ERROR: Mechanism not supported, …
> C_Digest: return len when output hash is NULL

- .ci/download-deps.sh
- tools/tpm2_pkcs11/commandlets_keys.py
Since upstream commit https://github.com/tpm2-software/tpm2-tss-engine/commit/06f57a300c0a60bdf9c5583f78af7f4335732eb0, tpm2-tss-engine uses `TPM2_RH_OWNER` instead of `0` as the value for the parent. This leads to a failure in the integration test `ptool-link.sh`:
```
+ tpm2_ptool link --label=linktokentransient --userpin=myuserpin --key-label=tss2rsa2048transient --path=/tmp/tmp.lSWQdwB0pe /tmp/tmp.lSWQdwB0pe/tss2-rsa-2048-transient.pem
The primary object (id: 2) is transient and the TSS Engine key has a parent handle, got: 0x40000001
```
> tpm2_ptool: make link command compatible with tpm2-tss-engine 1.1.0

- docs/SSH_HOSTKEYS.md
As discussed during a tpm.dev meeting here is WIP documentation for using tpm2-pkcs11 and ssh-agent for sshd host keys.
I did very basic testing now, but I have previously used a very similar setup (but with another PKCS11 module).
> [WIP] Add sshd hostkey documentation

- tools/tpm2_pkcs11/commandlets_token.py
When using option `--sopin` in `tpm2_ptool verify`, `usersealauth` is not initialized but is being used. In practise, the value in `verify_output['wrappingkey']['auth']` is the same as the one in `verify_output['pin']['user']`, so make sure this is set only when the user PIN is really used.
Fixes: https://github.com/tpm2-software/tpm2-pkcs11/issues/624
> Fix "tpm2_ptool verify --sopin" without "--userpin"

- test/unit/test_db.c
7 tests from test_db.c used an int type for sqlite3_last_insert_rowid,
which caused endian issue and test failed on s390 platform
Signed-off-by: SZ Lin (林上智) <szlin@debian.org>
Link: https://buildd.debian.org/status/fetch.php?pkg=tpm2-pkcs11&arch=s390x&ver=1.5.0-3&stamp=1611234144&raw=0
> Fix endian issue on s390x platform

- src/lib/encrypt.c
input was just created and coppied off of part but was never used, so
remove it.
> encrypt: remove unused allocated buffer

- tools/tpm2_pkcs11/tpm2.py
- tools/tpm2_pkcs11/utils.py
Using `raise RuntimeError("...: %s", something)` reports the tuple `("...: %s", something)`, which is unexpected. Replace such code with `%` in order to format the error with the parameter.
While at it, drop an unneeded `str()` when formatting
raise RuntimeError("Could not execute tpm2_import: %s" %
str(stderr))
because `%s` already calls `str()` on the formatted value.
> Always use % to format RuntimeError parameter

- configure.ac
- src/lib/backend_fapi.c
- src/lib/db.c
- src/lib/tpm.c
- src/lib/tpm.h
- test/unit/test_db.c
Commit 5b379c0d introduced a call to Esys_TR_GetTpmHandle() into a common code
path.  This function was only added to tss2-esys in version 2.4, and isn't
readily available in packaged distributions, yet. Only the FAPI backend
actually makes use of the function. Hence, splice out the call to a separate
function that can be conditionally included. (No matching stub is added for
tss2-esys < 2.4, so dependency errors can be caught already at compile time.)
This change restricts the versioned dependency on tss2-esys >= 2.4 to
FAPI-enabled builds, and thus facilitates standard builds of tpm2-pkcs11 on
current distributions.
Fixes: #632
Signed-off-by: Daniel Kobras <kobras@puzzle-itc.de>
> Relax tss2-esys versioned deps for non-FAPI builds

- src/lib/tpm.c
The last use of this function was removed in
dc83d34291cda8ebd05ed9eca6573a2b8b32f93e.
This fixes the build when compiling with clang.
> Remove unsued function tpm2_error_get

- src/lib/backend.c
Free the tmp variable as temp gets assigned to tok.
> Backend: free tmp not tok variable

- tools/tpm2_pkcs11/db.py
While testing tpm2_ptool with the wrong version of the tool (compared to the database), I got:
DB Upgrade failed: "DB Version exceeds library version: 5 > 4", backup located in "None"Traceback (most recent call last):
File "/usr/sbin/tpm2_ptool", line 33, in <module>
sys.exit(load_entry_point('tpm2-pkcs11-tools==1.33.7', 'console_scripts', 'tpm2_ptool')())
File "/usr/lib/python3.9/site-packages/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
File "/usr/lib/python3.9/site-packages/tpm2_pkcs11/command.py", line 102, in init
commandlet.get()[d['which']](d)
File "/usr/lib/python3.9/site-packages/tpm2_pkcs11/commandlets_store.py", line 91, in __call__
with Db(path) as db:
File "/usr/lib/python3.9/site-packages/tpm2_pkcs11/db.py", …
> tpm2_ptool: fix error message when the DB is too new

- src/lib/utils.h
Commit 9af101b54035 ("utils: fix stringop-overread in str_padded_copy") introduced a log message which is displayed every time the function `str_padded_copy` is used. This looks like a debug message used while working on the patch. Now that it is applied, remove the log message.
> utils: remove debug log message from str_padded_copy

- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/tpm2.py
Hello,
This Pull Request implements what was discussed in https://github.com/tpm2-software/tpm2-pkcs11/issues/659 : being to able to use `tpm2_ptool import` with OpenSSH keys.
In order to support encrypted private keys, I added option `--passin` exactly like `tpm2_import`. This enables importing encrypted PEM and DER private keys with all supported `--passin` variants (cf. `man 1 openssl`: https://www.openssl.org/docs/man1.1.1/man1/openssl.html#Pass-Phrase-Options). This option is also parsed when importing encrypted OpenSSH keys.
While at it, this PR also makes `--algorithm` optional, as the type of the private key (`ecc` or `rsa`) can be guessed from the PEM file header. This argument is still required when importing DER keys.
I did not write tests as I do not know how `tpm2_ptool` is …
> tpm2_ptool import: enable importing encrypted private keys and SSH private keys

- test/integration/PKCS11JavaTests.java
When using Debian 11 to run integration tests with openjdk-17-jdk, the integration checks fail:
FAIL: test/integration/pkcs11-javarunner.sh.java
This is because `System.getProperty("java.version")` is `"17-ea"` and does not contain any dot, even though the test expects the version to be something such as `11.0.11`.
Parse Java versions which use a `-ea` suffix without including any dot.
While at it, uniformize the indentation in order to use tabs.
> test/integration/PKCS11JavaTests: fix version parsing with openjdk-17-jdk

- test/integration/nss-tests.sh
- test/integration/openssl.sh
- test/integration/p11-tool.sh.nosetup
- test/integration/pkcs11-dbup.sh.nosetup
- test/integration/pkcs11-tool-init.sh.nosetup
- test/integration/pkcs11-tool.sh
- test/integration/ptool-link.sh.nosetup
- test/integration/python-pkcs11.sh
- test/integration/scripts/create_pkcs_store.sh
- test/integration/tls-tests.sh
When `test/integration/p11-tool.sh.nosetup` is called directly (for example when debugging issues related to `p11tool`), `$T` is not defined. Define this variable to the top-level directory using `${BASH_SOURCE[0]}` to make `p11-tool.sh.nosetup` directly invokable.
Repeat this change in all files which use `$T` in order to make debugging issues easier, even though running `make check TESTS=...` also enables running each test directly.
While at it, use this variable in the error message in order to produce a line which directly contains the path to the tested library `libtpm2_pkcs11.so`.
> test/integration: define variable T in all scripts

- test/integration/pkcs11-tool.sh
In `test/integration/pkcs11-tool.sh`, when `tpm2_testparms rsa3072` returns a failure, the test cases with `--algorithm="rsa3072"` are skipped. But the tests which come after, like the ones related to SSH keys, are also skipped.
As this behaviour seems unexpected, encapsulate the RSA3072 tests inside an if block. Moreover using `if` makes using `set +e`/`set -e` no longer necessary.
> test: do not skip SSH tests when RSA3072 is not supported

- docs/BUILDING.md
Hello,
Finding out all the dependencies which are required to run every integration test is quite painful. This PR documents how to use containers to launch tests, which helps maintaining the dependencies list.
Add a part to the `BUILDING` documentation which describes how to launch an Arch Linux and a Debian containers to install dependencies and run all tests. This also greatly helps setting up a development system for tpm2-pkcs11.
(This PR is a cleaned-up version of what I posted a few days ago when I tested another PR, https://github.com/tpm2-software/tpm2-pkcs11/pull/684#pullrequestreview-667972361)
> docs/BUILDING: document how to run tests in a container

- .lgtm.yml
Since https://github.com/tpm2-software/tpm2-tss/pull/2069 installing tpm2-tss from a snapshot of the master branch no longer works fine: even if `./configure` and `make install` work, there is a failure in the configure phase of tpm2-tools. Here is the build log from https://lgtm.com/projects/g/tpm2-software/tpm2-pkcs11/logs/rev/pr-ae3094acd9630566fa4cbea107ba5592740be8f9/lang:cpp/stage:Build%20master_06ca8f4f0d7d11f877cfe08a0a6d1f95f52ebee4
[2021-06-08 21:13:44] [build-stderr] ++ wget https://github.com/tpm2-software/tpm2-tss/archive/master.tar.gz
...
[2021-06-08 21:13:45] [build-stderr] ++ tar xf master.tar.gz
[2021-06-08 21:13:45] [build-stderr] ++ rm master.tar.gz
[2021-06-08 21:13:45] [build-stderr] ++ cd tpm2-tss-master
[2021-06-08 21:13:45] [build-stderr] ++ ./bootstrap
[2021-06-08 …
> LGTM: clone tpm2-tss and tpm2-tools repositories to fix the build

- src/lib/emitter.c
- src/lib/object.c
- src/lib/parser.c
- src/lib/token.c
- src/lib/token.h
- src/pkcs11.c
- test/integration/pkcs11-tool.sh
- test/integration/scripts/create_pkcs_store.sh
- test/integration/test.h
- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/commandlets_token.py
Using password-less SSH keys is a nice feature, which can be achieved in PKCS#11 by not setting `CKF_LOGIN_REQUIRED` in token information.
The information whether a PIN is empty or not is stored in a new attribute of the token configuration, named `empty-user-pin`. This attribute is set when `tpm2_ptool addtoken` is used with `--userpin=""` and it is updated when users change their PIN using `tpm2_ptool changepin` or `tpm2_ptool initpin`.
In `src/pkcs11.c`, update `auth_min_ro_user` in order to accept using functions such as `C_SignInit` without the user being logged in, when the user PIN is empty.
Regarding operations related to the TPM, using no user PIN is implemented as using an empty PIN. So table `sealobjects` is still used to unseal the wrapping key. The main difference between "no …
> Enable using objects with no user PIN

- tools/tpm2_pkcs11/tpm2.py
`mkstemp` returns an open file descriptor which needs to be closed. Ignoring its value (with `_`) does not close it.
Add missing `os.close()` to close these file descriptors.
> tpm2_ptool: do not leak the file description from mkstemp

- test/integration/fixtures/ossl-req-ca.cnf
- test/integration/fixtures/ossl-req-cert.cnf
- test/integration/openssl.sh
- test/integration/pkcs11-tool.sh
- test/integration/scripts/create_pkcs_store.sh
- tools/tpm2_pkcs11/utils.py
When using `tpm2_ptool addcert`, several users experienced issues because the signed data of the certificate was re-encoded when being added to the database. More precisely, the encoded certificate data is encoded using a BER encoder which encodes booleans using 1 of True (cf. https://github.com/etingof/pyasn1/blob/v0.4.8/pyasn1/codec/ber/encoder.py#L164). But in DER, the encoding of "True" is 0xff, and changing the signed data made the signature of the certificate no longer valid.
To fix this issue:
- Directly use the result of `pem.readPemFromFile(f)` in attribute `CKA_VALUE`: this is directly the encoded form of the certificate.
- Remove `pyasn1.codec.ber`, as this encoder is no longer used.
- Rename the DER decoder from `decoder` to `derdecoder` and the encoder from `derenc` to …
> tpm2_ptools: do not re-encode the signed data when importing a certificate

- tools/tpm2_pkcs11/commandlets_keys.py
- tools/tpm2_pkcs11/tpm2.py
Doing:
try:
privfd, tertiarypriv = mkstemp(prefix='', suffix='.priv', dir=d)
finally:
os.close(privfd)
can lead to issues when the call to `mkstemp` raises an exception, as `privfd` does not exist yet. Fix this issue by moving `mkstemp` out of the `try`/`finally` block.
When writing both the private and public files, in class `LinkCommand`, this change leads to intricated (and hard-to-understand) `try`/`finally` blocks. Reduce the complexity of the code by writing the files one after another.
Finally, introduce a `try`/`finally` block around an `os.write` call in function `importkey`, as it makes sense if the operating system raises an exception while writing the file (for example when the storage is full).
> tools: fix try/finally scope around os.write

- src/lib/db.c
Use the right bounds in the for loops when iterating over the mechanisms of AES and ECDSA keys.
Fixes: https://github.com/tpm2-software/tpm2-pkcs11/issues/710#issuecomment-929210228
> db: fix out of bound access chen updating the database

- src/lib/utils.c
clang's static analyzer reports a possible dereference of NULL pointer in `utils_setup_new_object_auth` when `newsalthex = NULL`, which is the case when this function is called from:
static inline CK_RV utils_new_random_object_auth(twist *newauthhex) {
return utils_setup_new_object_auth(NULL, newauthhex, NULL);
}
Check that the pointer is not NULL before dereferencing it.
> utils: do not dereference newsalthex if it is NULL

- src/lib/object.c
- test/integration/pkcs-sign-verify.int.c
> Do not use sequence to calculate expected ECDSA signature length

- src/lib/utils.h
The macro `set_safe_rc` is not used anywhere. It was introduced in commit 1bfdf34e4dfd ("db: negative test init_pobject_v3_from_stmt") without any user.
Remove this macro.
> utils: remove unused macro set_safe_rc

- src/lib/object.c
- test/integration/pkcs11-tool.sh
A friend tried to import a private RSA key using pkcs11-tool and got a strange state where the key seemed to be incorrectly imported.
The following commands can be used to reproduce this use-case:
openssl genrsa -out key-rsa.pem 2048
pkcs11-tool --module src/.libs/libtpm2_pkcs11.so --login --pin=XXXX \
--write-object key-rsa.pem --type privkey
The last command displays several warning messages but does not fail:
WARNING: Using default attribute handler for 291, consider registering a handler
WARNING: Guessing type for attribute, consider adding type info: 0x123
WARNING: Using default attribute handler for 292, consider registering a handler
WARNING: Guessing type for attribute, consider adding type info: 0x124
WARNING: Using default attribute handler for 293, consider registering a …
> object: properly reject importing RSA key

- test/integration/pkcs11-tool-init.sh.nosetup
Add a test to ensure that an SRK created with C_InitToken with an Owner
Hierarchy password set works.
Related-to: #777
> test: add test for C_InitToken SRK with owner password

- .ci/docker-prelude.sh
Docker runs in a root user container and the source code checkout is
done with some other UID. This causes git to complain its not a safe
directory so we need to mark it safe.
See the below link for details:
- https://github.blog/2022-04-12-git-security-vulnerability-announced/
This issue is not relevant for our disposable containers so we can
safely ignore this.
> ci: fix perms between clone and docker

- tools/tpm2_pkcs11/db.py
There are two issues with database upgrading. 
During an upgrade of the database to version 4, the config key 'persistent' is added instead of 'transient', causing KeyError when using the upgraded database.
After upgrading, there is no way to revert the database. This is a problem when no error is raised during the upgrade, but the database is upgraded incorrectly, like in the previous issue. This also is a problem when an error is raised during the upgrade, and the original database file is overwritten with the new one anyway. 
This pull fixes both of those issues.
Fixes #793.
> Fix database upgrading

- src/lib/tpm.c
I noticed that `tpm->use_createloaded` wasn't being set anywhere. 
I think this might be close to the correct functionality, but open to suggestions!
> Set use_createloaded

- Makefile-integration.am
- src/lib/attrs.c
- src/lib/derive.c
- src/lib/derive.h
- src/lib/mech.c
- src/lib/object.c
- src/lib/tpm.c
- src/lib/tpm.h
- src/lib/utils.c
- src/lib/utils.h
- src/pkcs11.c
- test/integration/pkcs-ecdh.int.c
- test/integration/pkcs11-tool.sh
Use TPM2_ECDH_ZGen as provided by tss2-esys (Esys_ECDH_ZGen()).
Test:
1) create two EC:prime256v1 keypairs (01, 02)
2) read 02 pubkey to pub2.der
3) --derive -m ECDH1-DERIVE --id 01 --input-file pub2.der --output-file /tmp/bytes1 
4)  read 01 pubkey to pub1.der
5) --derive -m ECDH1-DERIVE --id 02 --input-file pub1.der --output-file /tmp/bytes2 
6)  diff bytes1 bytes2
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
> lib: ecdh1 derive: simple implementation for KDF null

- tools/tpm2_pkcs11/db.py
Fix double conversion to int, causing a failing database upgrade.
> Fix failing database upgrade

- src/lib/db.c
- src/lib/db.h
- test/unit/test_db.c
Fix PKCS11_SQL_LOCK environent variable usage and add tests for lock file path creation.
Fixes: #820
> db: fix PKCS11_SQL_LOCK usage

- configure.ac
- docs/BUILDING.md
- test/integration/scripts/create_pkcs_store.sh
Update configure.ac to use AC_ARG_WITH and update the docs to the proper argument. Keep the option the same for downstream packagers.
Fixes: #822
> configure: update --with-fapi configure option

- configure.ac
The line
```
AX_CHECK_LINK_FLAG([[-Wl,--gc-sections]], [strip+="y$strip"])
```
is wrong. The += should be =.  So the subsequent test is never true, and chokes on dash because += is a bashism.
> configure: Change mistaken += to =

- src/lib/object.c
The PKCS#11 specification states:
- CKR_SESSION_READ_ONLY: The specified session was unable to accomplish the desired action because it is a read-only session.
However, the current implementation erroneously returns CKR_SESSION_READ_ONLY when a CKS_RW_PUBLIC_SESSION is detected, which contradicts the specification. Consequently, this leads to issues when adding certificates with NSS tools `certutil`. Typically, `certutil` initiates a CKS_RW_PUBLIC_SESSION; it only attempts a user login if it encounters the CKR_USER_NOT_LOGGED_IN error.
Script to reproduce the issue:
```
export TPM2_PKCS11_BACKEND="esysdb"
export NSSDB_DIR=$(mktemp -d)
cd $NSSDB_DIR
rm ./*
tpm2_clear -c p
rm -rf $TPM2_PKCS11_STORE
export TPM2_PKCS11_STORE=$(mktemp -d)
tpm2_ptool init --path $TPM2_PKCS11_STORE
tpm2_ptool …
```
> C_CreateObject should not return CKR_SESSION_READ_ONLY when a RW session is in use.

- src/lib/backend_fapi.c
When the FAPI backend is used, the following steps occur whenever `C_SetAttributeValue()` is invoked to update attributes. The function `backend_fapi_update_tobject_attrs()` performs these actions:
1. Invoke `Fapi_GetAppData()` to retrieve the existing `appdata`.
2. Find the offset (`tobj_start`) of the `tobj` to be deleted in the `appdata`.
3. Allocate a new buffer `newappdata`.
4. Copy only the data before `tobj_start` from `appdata` to `newappdata`:
```
memcpy(&newappdata[0], &appdata[0], tobj_start);
```
5. Append the new value (`attrs`) to `newappdata`:
```
sprintf((char*)&newappdata[tobj_start], "%08x:%s", tobj->id, attrs);
```
6. Append the remaining data from `appdata`:
```
memcpy(&newappdata[tobj_start + 9 + strlen(attrs) + 1],
&appdata[tobj_start + tobj_len], …
```
> [FAPI] Fix appdata corruption caused by offset miscalculation

- src/lib/db.c
This caused SEGFAULT when moving sql3 db from 1.7 to 1.9. With this fix I've managed to use old db successfully.
> Fix possible NULL pointer dereference.

- src/lib/tpm.c
Fixed a few apparent leaks that result from `Esys_CreatePrimary` allocating memory for its output arguments. These variables seem to freed in `tpm_create_persistent_primary` but not in `tpm_create_transient_primary_from_template` when the same function is called and it didn't seem like they were being used afterwards.
Noticed this leak while attempting to load this library multiple times in a long-running application.
> Fix memory leaks from Esys_CreatePrimary

- configure.ac
- docs/FAPI.md
- src/lib/backend.c
- src/lib/backend_fapi.c
This PR contains 2 minor FAPI cleanups
- Fix the help text to show enable-fapi rather than with-fapi to enable/disable the support
- Don't spit out a warning message about not being able to fetch from FAPI when it's not compiled in and it's not the selected backend
> Minor FAPI cleanups

- test/integration/p11-tool.sh.nosetup
Integration tests are failing when built against openssl 3.3.1, e.g:
```
+ openssl req -provider tpm2 -provider base -new -x509 -days 365 -subj '/CN=my key/' -sha256 -key /tmp/tpm_simulator_Ulvzcd/14.pem --passin pass:756dc95213a46b4249b1d3def6187339 -out /tmp/tpm_simulator_Ulvzcd/cert.pem.ec1
req: Unknown option or message digest: sha256
req: Use -help for summary.
```
This appears to be because neither the `base` nor `tpm2` providers currently support the sha256 symmetric cipher algorithm, although it can be enabled in `tpm2-openssl` [at compile time](https://github.com/tpm2-software/tpm2-openssl/blob/master/docs/INSTALL.md#building-from-source).
Using the `default` provider instead of `base` fixes tests that are currently failing.
I've submitted this patch to the [Arch Linux …
> Swap openssl base provider for default provider in integration tests

- Makefile.am
The fuzz tests need fake-tpm so add it to the distribution tarball generated via make dist.
Fixes: #854
> dist: add fake-tpm to release tarball

- src/lib/db.c
- tools/tpm2_ptool/tpm2_pkcs11/command.py
For newly created DBs, following the general practice on Linux (and tpm2-tss, which already uses ~/.local/share/tpm2-tss/ for FAPI).
The old ~/.tpm_pkcs11/ path is supposed to be still used if it exists, assuming I got the logic right, but I'm really not sure if the db.c part of it is correct.
> prefer ~/.local/share/ as the data directory (WIP)

- tools/setup.py
Building with recent setuptools shows the following warning:
/usr/lib/python3.13/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
Given that the list is empty, I think removing it altogether is ok.
> Remove deprecated tests_require

- tools/tpm2_pkcs11/objects.py
While it's a legacy algorithm, all the other lists (ECDSA, RSA-PSS, HMAC) do include it.
> add SHA1-RSA-PKCS to CKM_ALLOWED_MECHANISMS

- test/integration/scripts/helpers.sh
The latest update of the opensuse-leap container uses a new path schema:
/usr/lib64/clang/17/lib/linux/libclang_rt.asan-x86_64.so
> Fix detection of libasan location in CI tests

- configure.ac
- src/lib/attrs.c
- src/lib/attrs.h
- src/lib/object.c
- test/integration/p11-tool.sh.nosetup
- test/integration/pkcs11-tool.sh
- test/integration/scripts/create_pkcs_store.sh
have_javac and the tricks we use to make AX_PROG_JAVAC to be non fatal are not stable across versions of the macro. Use JAVAC as that's a stable variable to test for javac with.
> random fixes

- configure.ac
Without -Wformat for -Wformat-security, gcc will complain:
checking whether the C compiler accepts -Wformat-security... no configure: error: Cannot enable -Wformat-security, consider configuring with --disable-hardening
Related to: https://github.com/tpm2-software/tpm2-pkcs11/pull/899
> configure: add -Wformat to CFLAGS

- CHANGELOG.md
- Split incorrect combined entry "tpm2_ptool destroy removal error on persistent pobjects" into two separate items:
- Add support for importing persistent TPM2 keys with tpm2_ptool
- Fix tpm2_ptool destroy command failures
- Typos
No functional changes, documentation only.
> CHANGELOG: fix changelog for 1.9.2-rc0
