docs/BUILDING.md, docs/INITIALIZING.md, docs/README.md, src/lib/db.c, tools/tpm2_ptool.py
1. Add a document describing initalization
2. Minor fixes for path handling
=> add initialization document

docs/README.md, docs/SSH.md
Add an example of how to configure and set up a local SSH
connection.
=> docs: add SSH example

Makefile.am
Fix the errors reported by make dist.
=> make: fix make dist

tools/tpm2_ptool.py
=> tpm2_ptool.py: remove unused import

Makefile.am, src/lib/db.c, src/lib/session_ctx.c, src/lib/token.h, src/lib/utils.c, src/lib/utils.h, test/.gitignore, test/integration/pkcs-sign-verify.int.c, test/integration/scripts/create_pkcs_store.sh, tools/tpm2_ptool.py
* Allow for the ability to use SW based object auth wrapping - fixes support when tpm doesn't have encrypt/decrypt command #15 .
* Detect maximum aes key size support - fixes aes key size issues when tpm doesn't support 256 #25
=> core: support software auth value protections and maximum aes key sizes

Makefile.am, configure.ac, misc/p11-kit/tpm2_pkcs11.module, src/lib/db.c, src/lib/slot.c
Get working with P11 kit
Fixes: #28
=> configure: change install locations if P11 kit detected

test/integration/scripts/create_pkcs_store.sh, tools/tpm2_ptool.py
William Roberts (3):
tpm2_ptool.py: support existing primary keys
tpm2_ptool.py: use argparse for path expansion
tpm2_ptool.py: fix token to wrapping obj mapping
=> support existing primary keys

src/lib/mutex.h, src/lib/session.c, src/lib/session_table.c, src/lib/session_table.h, src/lib/tpm.c
William Roberts (2):
mutex: fix some locking issues
mutex: enable lock/unlock logs
=> Fix some locking

docs/P11.md, docs/README.md
Document some working p11kit and p11tool usages.
=> p11kit and p11tool: document p11 usages

.ci/coverity.run, .ci/docker-prelude.sh, .ci/docker.run, .ci/download-deps.sh, bootstrap, docs/BUILDING.md
* 0f02b63e5f94 bootstrap: allow options to autoreconf
* e37bb259c34b ci: add autoconf-archive to docker image
=> m4: update m4 installation methods

docs/P11.md, tools/tpm2_ptool.py
Very minor tweaks I made whilst taking a look over the docs and tpm2_ptool
=> Minor fixes

src/lib/checks.h, src/lib/db.c, src/lib/db.h, src/lib/digest.c, src/lib/encrypt.c, src/lib/general.c, src/lib/key.c, src/lib/object.c, src/lib/object.h, src/lib/random.c, src/lib/session.c, src/lib/session.h, src/lib/session_ctx.c, src/lib/session_ctx.h, src/lib/session_table.c, src/lib/session_table.h, src/lib/sign.c, src/lib/slot.c, src/lib/token.c, src/lib/token.h, test/integration/pkcs-login-logout.int.c, test/integration/pkcs-misc.int.c, test/integration/pkcs-open-close-session.int.c, test/integration/test.h
* move the session table to token scope
* test that C-CloseAllSessions() stays within token scope
Fixes: #74
Fixes: #5
=> Session table token scope

Makefile.am, src/lib/session_ctx.c
The testing framework broke, silently. Fix it and get it running again, Fixing an introduced bug.
=> fix testing

docs/PKCS11_TOOL.md, docs/README.md, src/lib/db.c, src/lib/db.h, src/lib/object.h, src/lib/slot.c, src/lib/token.c, src/lib/token.h, src/lib/tpm.c, src/lib/tpm.h, src/lib/twist.c, src/lib/twist.h, src/lib/utils.c, src/lib/utils.h, src/pkcs11.c, test/integration/pkcs-login-logout.int.c, test/integration/test.h
Implement C_SetPIN PKCS11 interface and add integration tests.
Fixes: #112
=> C_SetPIN: implement interface

docs/PKCS11_TOOL.md, src/lib/db.c, src/lib/token.c, src/lib/token.h, src/lib/tpm.c, src/lib/tpm.h, src/pkcs11.c, test/integration/pkcs-login-logout.int.c
Implement the C_InitPin logic and add a test.
Fixes: #111
=> C_InitPin - implement interface and test

src/lib/digest.c, src/lib/digest.h, src/lib/encrypt.c, src/lib/sign.c, src/lib/sign.h, src/lib/tpm.c, test/integration/pkcs-crypt.int.c, test/integration/pkcs-sign-verify.int.c
=> Double sign get size fix

.ci/docker.run, src/lib/token.c, tools/tpm2_pkcs11/tpm2.py
=> ci: fix ci

src/lib/log.h
=> Make logging more robust

tools/setup.py, tools/tpm2_pkcs11/tpm2.py
setup.py to have long_description field and now twine check is happy
And then move tmpfile creation after error handling so they are not left dangling.
=> Misc fixes on python part

Makefile.am, test/unit/test_log.c
Since there is no real way to test the log function,
we should atleast add a simple test that excercises the code paths.
=> Tests: Add simple test for logging

src/lib/sign.c, test/integration/pkcs-sign-verify.int.c
The function ec_fixup_size was not implemented correctly,
as the initial logic whether the fixup should be applied was inverted.
Moreover the function was only called if do_hash was set to true,
which is not the case for 'raw' ECDSA.
Fixes: 62a521d4964c8af03d886920be52047b4d60fe44
Fixes: #201
=> Fix Buffer Size for ECDSA

test/integration/pkcs-keygen.int.c
Quite a lot of fields can be omitted from the keygen template,
however no code ever tested this.
-> Add a testcase
=> Add testcase for rsa keygen with missing fields from template

src/lib/sign.c, test/integration/pkcs-keygen.int.c
In the special case of CKM_RSA_PKCS and other 'raw' hashes the sign operation
has to call the tpm for a decrypt which increases the internal reference
counters. Unfortunately these counters were not reset correctly.
Without breaking the existing logic and reworking everything,
the sign operation has to take care that the counters are decremented.
Fixes: #238
=> Fix reference counting for CKM_RSA_PKCS

tools/tpm2_pkcs11/commandlets_store.py, tools/tpm2_pkcs11/commandlets_token.py
(Token public/private data has been stored in the DB as blobs since #124.)
Fixes: #247
=> Removed RmTokenCommand.rmtokenfiles, vestigal references to token files.

.lgtm.yml, docs/README.md, tools/tpm2_pkcs11/commandlets_keys.py, tools/tpm2_pkcs11/commandlets_store.py, tools/tpm2_pkcs11/commandlets_token.py, tools/tpm2_pkcs11/db.py, tools/tpm2_pkcs11/tpm2.py, tools/tpm2_pkcs11/utils.py
[LGTM](https://lgtm.com/) is a code analysis platform that scans code for known vulnerabilities and problematic patterns. It is already [enabled for tpm2-tss](https://github.com/tpm2-software/tpm2-tss/issues/1475), but using it in this project as well requires some additional help in form of a [`.lgtm.yml` configuration file](https://lgtm.com/help/lgtm/lgtm.yml-configuration-file) in order to build and install tpm2-tss from source in LGTM's build environment. This configuration will allow to analyse the code in this project, cf. the [successful test build](https://lgtm.com/logs/35bc16341a4ecfafa400334eeea53341e4362abb/lang:cpp). No further action other than merging this PR is necessary, new code is [fetched automatically once a day](https://lgtm.com/help/lgtm/analysis-faqs#how-often-does-l …
=> ci: add LGTM

test/integration/scripts/int-test-setup.sh
Signed-off-by: Matthew Dempsky <matthew@dempsky.org>
=> Fix typo: s/tarbmd/tabrmd/

src/lib/config.h.in
=> autoconf: update config.h.in

src/lib/object.c
=> C_FindObjects: fix no objects shown unless logged in

tools/setup.py
=> tpm2_ptool: setup.py dependency add pyasn1_modules

Makefile.am, src/lib/token.c, test/integration/pkcs11-tool.sh, test/integration/scripts/create_pkcs_store.sh, tools/tpm2_pkcs11/commandlets_token.py, tools/tpm2_pkcs11/tpm2.py
- add pkcs11-tool test script
- fix tpm2_ptool verify
- yamalize tpm2_ptool output
=> testing: add pkcs11-tool test script

src/lib/db.c
=> db: remove traling 1 in tokid select

src/lib/db.c
=> db: fix trailing 1 in select sealobjects

.gitignore
Ignore test generated files:
test_attr
test_parser
test_log
Signed-off-by: Imran Desai <imran.desai@intel.com>
=> gitignore: Updated to ignore outputs at end of test runs

CHANGELOG.md, Makefile.am, src/lib/db.c, src/lib/digest.c, src/lib/encrypt.c, src/lib/encrypt.h, src/lib/object.c, src/lib/sign.c, src/lib/token.c, src/lib/tpm.c, src/lib/tpm.h, src/lib/utils.c, test/integration/openssl.sh, test/integration/pkcs-crypt.int.c
=> Fix rsa crypto

Makefile.am, src/lib/db.c, src/lib/db.h, src/lib/object.c, src/lib/object.h, src/lib/token.c, src/lib/token.h
- Add a check-programs target to help with refactoring
- Cleanup and minor refactor db / token / object headers and c files
=> Minor fixes to the token/tb interaction

test/integration/PKCS11JavaTests.java
The test submitted appears to be working on master now, so something fixes it.
Fixes: #401
=> Java sign fix

test/integration/pkcs-keygen.int.c
Fix the portion of the test where it uses C_Encrypt with an RSA Public
Key and C_Decrypt with an RSA Private key.
Fixes: #384
=> test: uncomment and fix RSA C_Encrypt test

src/lib/tpm.c
and using rsa RSA -> and using raw RSA
I think that raw RSA is the correct statement, feel free to ignore this PR otherwise!
=> Update comment in tpm.c

.travis.yml
=> ci: test against opensuse-leap

src/lib/config.h.in, src/lib/tpm.c
- Add the ESYS_3 define to the config.h.in
- Fix some UAF errors
=> random fixes

Makefile.am, src/lib/backend.c, src/lib/backend_esysdb.c, src/lib/backend_fapi.c, src/lib/config.h.in, test/integration/pkcs11-tool-init-fapi.sh.fapi, test/integration/pkcs11-tool-init.sh.nosetup, test/integration/scripts/int-test-funcs.sh, test/integration/scripts/int-test-setup.sh
This fixes most comments from #414 as well as #451 and #453 
Depends on https://github.com/tpm2-software/tpm2-software-container/pull/31
=> Fixes for FAPI backend

.ci/docker-prelude.sh, Makefile.am, configure.ac, test/integration/p11-tool-fapi.sh.fapi, test/integration/p11-tool.sh.nosetup
This should work, one p11tool is part of the docker containers.
=> Add p11tool tests

CHANGELOG.md, Makefile.am, src/lib/attrs.c, src/lib/attrs.h, src/lib/backend.c, src/lib/backend.h, src/lib/backend_esysdb.c, src/lib/backend_esysdb.h, src/lib/db.c, src/lib/db.h, src/lib/object.c, src/lib/object.h, src/lib/typed_memory.c, src/lib/typed_memory.h, src/pkcs11.c, test/integration/pkcs-get-attribute-value.int.c
=> Support C_SetAttributeValue

src/lib/backend.c
=> backend: remove superfluous warnings

Makefile.am, src/lib/backend.c, src/lib/backend_fapi.c, src/lib/backend_fapi.h, test/integration/scripts/int-test-funcs.sh
My problem: I don't know how to test UpdateAttributes for FAPI backend right now.
Can this be triggered by pkcs11-tool or p11-tool ?
(includes #482)
Fixes #471 
Fixes #472
=> FAPI: Add delete and set attribute

src/lib/backend.c
Currently, FAPI errors in intializing and listing are treated as fatal
errors even when FAPI_PREVIEW is not enabled. Treat errors as warnings
unless FAPI_PREVIEW is enabled.
Fixes: #480
=> FAPI: Treat backend errors as warnings

.gitignore, Makefile-fuzz.am, Makefile-integration.am, Makefile-unit.am, Makefile.am, configure.ac, docs/FUZZING.md, src/lib/config.h.in, src/lib/db.c, src/lib/parser.c, test/fuzz/scripts/fuzz-runner.sh, test/fuzz/yaml-parser.fuzz.c
- Add A Fuzzing Target
- Fix some NPD's discovered by fuzzing target
=> Add First Fuzzing Target

src/lib/backend_esysdb.c, src/lib/session_ctx.c, src/lib/token.c, src/lib/token.h, src/lib/tpm.c, src/lib/tpm.h, test/fuzz/init-token.fuzz.c
Some refactoring that should help the FAPI transition and hopefully make sense in general...
=> Some refactoring

src/lib/db.c
=> db: add step to updating attrs

src/lib/backend.c, src/lib/backend_fapi.c, src/lib/db.c, src/lib/tpm.c, src/lib/tpm.h, test/integration/p11-tool.sh.nosetup
=> Fapi: Set correct tcti for esys operations

.gitignore, Makefile-fuzz.am, test/fake-tpm/wrap_tpm.h, test/fuzz/init-pin.fuzz.c
Make sure that input to C_InitPin doesn't have unexpected issues.
=> fuzz C_InitPin user pin values

Makefile-integration.am, configure.ac, src/lib/backend.c, src/lib/backend_fapi.c, src/lib/db.c, src/lib/tpm.c, src/lib/tpm.h
Followup of #504 with https://github.com/tpm2-software/tpm2-tss/pull/1719 based changes
=> Full FAPI (SRK) support and adapt to new FAPI auth cbs

CHANGELOG.md
=> CHANGELOG: Add note on backends and fapi

src/lib/attrs.c, src/lib/object.c, src/lib/token.c
Some things are just silencing the analysis tools.
=> Some fixes from scanbuild and coverity

src/lib/db.c
Fix an issue found by clang-10 scanner.
=> Scan build fixes

.ci/coverity.run, .ci/travis.run, .travis.yml, docs/README.md, src/lib/mech.c
Update the travis.run file and pull out some of the magic values
and assign to global statics.
=> ci: update travis run

src/lib/token.c
=> init_token: use memchr over loop

test/integration/scripts/create_pkcs_store.sh, tools/tpm2_pkcs11/commandlets_keys.py
- a18bf6341d94 tpm2_ptool: support ecc import
- dbb7515a19c9 tpm2_ptool: remove checks in import commandlet
Fixes: #546
=> tpm2_ptool: import algorithm option updates, support ECC

docs/BUILDING.md, docs/INSTALL.md
=> Move ptool install instructions

src/lib/token.c
=> token: add missing LOGE("oom")

README.md
Just so folks can find it a bit quicker when not being displayed by
github.
=> README: a root README.md that is a link to docs/README.md

src/lib/tpm.c
Silence errors about using Esys_EncryptDecrypt2 when not supported by the TPM and falling back to Esys_EncryptDecrypt by checking the capabilities to see if it supports EncryptDecrypt2 first.
Fixes: #566
=> Check for enc dec 2

docs/OPENVPN.md
=> docs/OPENVPN.md: change PKCS to PSS

test/unit/test_db.c
=> test_db: fixup unused variable warnings

Makefile-unit.am, src/lib/emitter.h, test/unit/test_db.c
@diabonas this should fix the build hopefully
=> test_db: add missing RV checks

src/lib/session_table.c, test/integration/pkcs-session-state.c
The cod had a big TODO to fix an issue with C_OpenSession. The code
should be searching the session table for an open handle rather than
using a open handle tracking variable, becuase currently, they can
exhaust the table and cause an OOB issue. Also, when the assert is
compiled out on release, NPD can also occur.
Also update the valid handle range to NOT include 0, since per the spec:
Valid session handles in Cryptoki always have nonzero values.
For developers’ convenience, Cryptoki defines the following symbolic value:
CK_INVALID_HANDLE
Fixes: #612
=> C_OpenSession: search for open handle

src/lib/digest.c, test/integration/pkcs-misc.int.c
=> C_Digest: Fix 5.2 style returns

src/lib/digest.c, src/lib/mech.c, src/lib/tpm.c, test/integration/pkcs-misc.int.c
Fix defects detected by the coverity scan at:
- https://scan.coverity.com/projects/tpm2-pkcs11?tab=overview
=> Fix coverity defects

CHANGELOG.md, src/lib/backend.c, src/lib/tpm.c, src/lib/utils.h
=> merge 1.X into Master

src/lib/tpm.c
Signed-off-by: 张亚 <zhangya@uniontech.com>
=> fix: Esys_GetRandom memory leak

docs/SSH_HOSTKEYS.md
=> docs: fix typo on HostHostKeyAgent

docs/INITIALIZING.md
You only see public parts when NOT logged in, not the other way around.
=> FIxed a bad statement

docs/RELEASE.md
=> update mailing list

docs/MAINTAINERS.md
=> MAINTAINERS: add Andreas and Juergen

test/integration/nss-tests.sh
Add the integration tests for PRs #859 and #860
=> Add the integration tests for PRs #859 and #860

test/integration/pkcs11-tool.sh, test/integration/ptool-link.sh.nosetup
- Fix typos in test/integration/pkcs11-tool
- Fix stability issue in test/integration/pkcs11-tool.sh
=> Fix integration test stability issues

docs/INITIALIZING.md
Fixed incorrect use of tokens instead of objects, proposal in PR.
=> Removed redundant 'Tokens' and replaced with 'objects' in Readme

src/lib/key.c, src/lib/object.c, src/lib/object.h, src/lib/session_ctx.c, src/lib/token.c, src/lib/tpm.c
=> Rename tobject.tpm_handle to tpm_esys_tr for clarity
